Libreame\BackendBundle\Entity\LbTratos:
    type: entity
    table: lb_tratos
    indexes:
        fk_lb_tratos_lb_ofertas1_idx:
            columns:
                - inTraOferta
        fk_lb_tratos_lb_usuarios1_idx:
            columns:
                - inTraUsuOfrecio
        fk_lb_tratos_lb_usuarios2_idx:
            columns:
                - inTraUsuAcepto
    id:
        intrato:
            type: integer
            nullable: false
            unsigned: false
            comment: Id
            id: true
            column: inTrato
            generator:
                strategy: IDENTITY
    fields:
        intrafecha:
            type: datetime
            nullable: false
            comment: 'Fecha en la que se cierra el trato (se actualiza cuando cada usuario acepta.)'
            column: inTraFecha
        intraestado:
            type: integer
            nullable: false
            unsigned: false
            comment: "0: Cerrado (Acabo de cerrar el trato)\n1: Cumplido por ambas partes\n2: Incumplido por Oferente\n3: Inclumplido por Acepto \n4. En proceso (Cerrado pero no realizado fisicamente aun)\n5. Incumplido por ambos (Cuando ninguno de los dos marcó el hecho de su realización)"
            default: '0'
            column: inTraEstado
        txtraacuentrega:
            type: string
            nullable: false
            length: 500
            fixed: false
            comment: 'Permite indicar lugares, acuerdos y condiciones particulares de la entrega'
            column: txTraAcuEntrega
        fetrafecentrega:
            type: datetime
            nullable: false
            comment: 'Fecha y hora acordada para la entrega.'
            column: feTraFecEntrega
    manyToOne:
        intraoferta:
            targetEntity: LbOfertas
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                inTraOferta:
                    referencedColumnName: inOferta
            orphanRemoval: false
        intrausuofrecio:
            targetEntity: LbUsuarios
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                inTraUsuOfrecio:
                    referencedColumnName: inUsuario
            orphanRemoval: false
        intrausuacepto:
            targetEntity: LbUsuarios
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                inTraUsuAcepto:
                    referencedColumnName: inUsuario
            orphanRemoval: false
    lifecycleCallbacks: {  }
