SELECT * FROM lb_autores;

delete FROM lb_autores where inIdAutor > 0;
alter table lb_autores auto_increment=1;
commit;
commit;commit;
commit;commit;
commit;commit;
commit;

INSERT INTO lb_autores (txAutNombre) VALUES ('Aaron Copland');
INSERT INTO lb_autores (txAutNombre) VALUES ('Abraham Silberschatz');
INSERT INTO lb_autores (txAutNombre) VALUES ('Adela Páez Muñoz');
INSERT INTO lb_autores (txAutNombre) VALUES ('Adolfo Bioy');
INSERT INTO lb_autores (txAutNombre) VALUES ('Adolfo Pérez Agusti');
INSERT INTO lb_autores (txAutNombre) VALUES ('Agatha Christie');
INSERT INTO lb_autores (txAutNombre) VALUES ('Agustín Barrios Sarmiento');
INSERT INTO lb_autores (txAutNombre) VALUES ('Albert Einstein');
INSERT INTO lb_autores (txAutNombre) VALUES ('Alberto Vázquez-Figueroa');
INSERT INTO lb_autores (txAutNombre) VALUES ('Alden Bell');
INSERT INTO lb_autores (txAutNombre) VALUES ('Aldous Huxley');
INSERT INTO lb_autores (txAutNombre) VALUES ('Alejandro Casona');
INSERT INTO lb_autores (txAutNombre) VALUES ('Alejandro Dumas');
INSERT INTO lb_autores (txAutNombre) VALUES ('Alejo Carpentier');
INSERT INTO lb_autores (txAutNombre) VALUES ('Alex Robertson');
INSERT INTO lb_autores (txAutNombre) VALUES ('Alexander Sergeyevich Pushkin');
INSERT INTO lb_autores (txAutNombre) VALUES ('Alexandr Ivanovich Oparin');
INSERT INTO lb_autores (txAutNombre) VALUES ('Alfred V. Aho');
INSERT INTO lb_autores (txAutNombre) VALUES ('Alfredo Brayce Echenique');
INSERT INTO lb_autores (txAutNombre) VALUES ('Alfredo Iriarte');
INSERT INTO lb_autores (txAutNombre) VALUES ('Alfredo Molano');
INSERT INTO lb_autores (txAutNombre) VALUES ('Álvaro Mutis');
INSERT INTO lb_autores (txAutNombre) VALUES ('Álvaro Salom Becerra');
INSERT INTO lb_autores (txAutNombre) VALUES ('Amanda Maris');
INSERT INTO lb_autores (txAutNombre) VALUES ('Amira de la Rosa');
INSERT INTO lb_autores (txAutNombre) VALUES ('Ana Carrigan');
INSERT INTO lb_autores (txAutNombre) VALUES ('Ana María Díaz Collazos');
INSERT INTO lb_autores (txAutNombre) VALUES ('Ana María Guiraldes');
INSERT INTO lb_autores (txAutNombre) VALUES ('Ana María Machado');
INSERT INTO lb_autores (txAutNombre) VALUES ('Andres Caicedo Estela');
INSERT INTO lb_autores (txAutNombre) VALUES ('Andres Hurtado García');
INSERT INTO lb_autores (txAutNombre) VALUES ('Andrés Oppenheimer');
INSERT INTO lb_autores (txAutNombre) VALUES ('Angela Becerra');
INSERT INTO lb_autores (txAutNombre) VALUES ('Angela Sommer-Bodenburg');
INSERT INTO lb_autores (txAutNombre) VALUES ('Angeles Doñate ');
INSERT INTO lb_autores (txAutNombre) VALUES ('Angeles Mastreta');
INSERT INTO lb_autores (txAutNombre) VALUES ('Aníbal Tobón');
INSERT INTO lb_autores (txAutNombre) VALUES ('Anicio Boeciuo');
INSERT INTO lb_autores (txAutNombre) VALUES ('Anita Brookner');
INSERT INTO lb_autores (txAutNombre) VALUES ('Antonio Santa Ana');
INSERT INTO lb_autores (txAutNombre) VALUES ('Aristóteles');
INSERT INTO lb_autores (txAutNombre) VALUES ('Arthur Conan Doyle');
INSERT INTO lb_autores (txAutNombre) VALUES ('Arthur Golden');
INSERT INTO lb_autores (txAutNombre) VALUES ('Arthur Schopenhauer');
INSERT INTO lb_autores (txAutNombre) VALUES ('Arturo Pérez-Reverte');
INSERT INTO lb_autores (txAutNombre) VALUES ('Arturo Uslar Petri');
INSERT INTO lb_autores (txAutNombre) VALUES ('Assiac');
INSERT INTO lb_autores (txAutNombre) VALUES ('Augusto Cury');
INSERT INTO lb_autores (txAutNombre) VALUES ('Aurelio Baldor');
INSERT INTO lb_autores (txAutNombre) VALUES ('Axis');
INSERT INTO lb_autores (txAutNombre) VALUES ('B.F. Skinner');
INSERT INTO lb_autores (txAutNombre) VALUES ('Beatriz Ferro');
INSERT INTO lb_autores (txAutNombre) VALUES ('Beatriz Helena Robledo');
INSERT INTO lb_autores (txAutNombre) VALUES ('Benito Pérez Galdos');
INSERT INTO lb_autores (txAutNombre) VALUES ('Benjamin Freeman');
INSERT INTO lb_autores (txAutNombre) VALUES ('Benjamin Sampson');
INSERT INTO lb_autores (txAutNombre) VALUES ('Blue Jeans');
INSERT INTO lb_autores (txAutNombre) VALUES ('Boris Vian');
INSERT INTO lb_autores (txAutNombre) VALUES ('Brian L. Weiss');
INSERT INTO lb_autores (txAutNombre) VALUES ('C. Henry Edwards');
INSERT INTO lb_autores (txAutNombre) VALUES ('C.K. Prahalad');
INSERT INTO lb_autores (txAutNombre) VALUES ('Camilo Chaparro');
INSERT INTO lb_autores (txAutNombre) VALUES ('Camilo Cruz');
INSERT INTO lb_autores (txAutNombre) VALUES ('Camilo José Cela');
INSERT INTO lb_autores (txAutNombre) VALUES ('Carl Sagan');
INSERT INTO lb_autores (txAutNombre) VALUES ('Carlos Arango Z');
INSERT INTO lb_autores (txAutNombre) VALUES ('Carlos Castañeda');
INSERT INTO lb_autores (txAutNombre) VALUES ('Carlos Cuautemoc Sánchez');
INSERT INTO lb_autores (txAutNombre) VALUES ('Carlos Fuentes');
INSERT INTO lb_autores (txAutNombre) VALUES ('Carlos García Gual');
INSERT INTO lb_autores (txAutNombre) VALUES ('Carlos Lira Vasquez');
INSERT INTO lb_autores (txAutNombre) VALUES ('Carlos Medina Gallego');
INSERT INTO lb_autores (txAutNombre) VALUES ('Carlos Ruiz Zafón');
INSERT INTO lb_autores (txAutNombre) VALUES ('Carlos Sabino');
INSERT INTO lb_autores (txAutNombre) VALUES ('Carroll Lewis');
INSERT INTO lb_autores (txAutNombre) VALUES ('Cecil Murphey');
INSERT INTO lb_autores (txAutNombre) VALUES ('Celso Román');
INSERT INTO lb_autores (txAutNombre) VALUES ('César A. Becerra Santamaría');
INSERT INTO lb_autores (txAutNombre) VALUES ('César Pérez');
INSERT INTO lb_autores (txAutNombre) VALUES ('Cesare Pavese');
INSERT INTO lb_autores (txAutNombre) VALUES ('Chaim Perelman ');
INSERT INTO lb_autores (txAutNombre) VALUES ('Charles Dickens');
INSERT INTO lb_autores (txAutNombre) VALUES ('Charles y Mary Lamb');
INSERT INTO lb_autores (txAutNombre) VALUES ('Christine Nostlinger');
INSERT INTO lb_autores (txAutNombre) VALUES ('Christopher Silvester');
INSERT INTO lb_autores (txAutNombre) VALUES ('Círculo de Lectores');
INSERT INTO lb_autores (txAutNombre) VALUES ('Clara Rojas');
INSERT INTO lb_autores (txAutNombre) VALUES ('Claude Levi-Strauss');
INSERT INTO lb_autores (txAutNombre) VALUES ('Colección Navegante');
INSERT INTO lb_autores (txAutNombre) VALUES ('Colleen McCullough');
INSERT INTO lb_autores (txAutNombre) VALUES ('Conrado Zuluaga');
INSERT INTO lb_autores (txAutNombre) VALUES ('Cooper Patrick');
INSERT INTO lb_autores (txAutNombre) VALUES ('Cristina Rivera Garza');
INSERT INTO lb_autores (txAutNombre) VALUES ('Cristopher Paul Curtis');
INSERT INTO lb_autores (txAutNombre) VALUES ('D.H. Lawrence');
INSERT INTO lb_autores (txAutNombre) VALUES ('Daladier Jabba Molinares');
INSERT INTO lb_autores (txAutNombre) VALUES ('Daniel Defoe');
INSERT INTO lb_autores (txAutNombre) VALUES ('Daniel Goleman');
INSERT INTO lb_autores (txAutNombre) VALUES ('Daniel Herrera Restrepo');
INSERT INTO lb_autores (txAutNombre) VALUES ('Daniel Samper Ospina');
INSERT INTO lb_autores (txAutNombre) VALUES ('Daniel Samper Pizano');
INSERT INTO lb_autores (txAutNombre) VALUES ('Daniel Yergin');
INSERT INTO lb_autores (txAutNombre) VALUES ('Dante Alighieri');
INSERT INTO lb_autores (txAutNombre) VALUES ('Darcy Pattison');
INSERT INTO lb_autores (txAutNombre) VALUES ('Dario Fritz');
INSERT INTO lb_autores (txAutNombre) VALUES ('Daron Acemoglu');
INSERT INTO lb_autores (txAutNombre) VALUES ('David Bushnell');
INSERT INTO lb_autores (txAutNombre) VALUES ('David Kaplan');
INSERT INTO lb_autores (txAutNombre) VALUES ('David Martín del Campo');
INSERT INTO lb_autores (txAutNombre) VALUES ('David Ricardo');
INSERT INTO lb_autores (txAutNombre) VALUES ('David Servan Schreiber');
INSERT INTO lb_autores (txAutNombre) VALUES ('David Thomson');
INSERT INTO lb_autores (txAutNombre) VALUES ('David Vásquez Hurtado');
INSERT INTO lb_autores (txAutNombre) VALUES ('Deepak Chopra');
INSERT INTO lb_autores (txAutNombre) VALUES ('Denis Diderot');
INSERT INTO lb_autores (txAutNombre) VALUES ('Denis Stevens');
INSERT INTO lb_autores (txAutNombre) VALUES ('Dhirendra Kumar');
INSERT INTO lb_autores (txAutNombre) VALUES ('Didier Anzieu');
INSERT INTO lb_autores (txAutNombre) VALUES ('Dominique La pierre');
INSERT INTO lb_autores (txAutNombre) VALUES ('Don Piper');
INSERT INTO lb_autores (txAutNombre) VALUES ('Doreen Virtue');
INSERT INTO lb_autores (txAutNombre) VALUES ('Douglas Adams');
INSERT INTO lb_autores (txAutNombre) VALUES ('Duran Moreno');
INSERT INTO lb_autores (txAutNombre) VALUES ('E L James');
INSERT INTO lb_autores (txAutNombre) VALUES ('Earl W. Swokowski');
INSERT INTO lb_autores (txAutNombre) VALUES ('Edgar Allan Poe');
INSERT INTO lb_autores (txAutNombre) VALUES ('Eduardo Caballero Calderón');
INSERT INTO lb_autores (txAutNombre) VALUES ('Eduardo Galeano');
INSERT INTO lb_autores (txAutNombre) VALUES ('Eduardo H Galeano ');
INSERT INTO lb_autores (txAutNombre) VALUES ('Eduardo Mendoza');
INSERT INTO lb_autores (txAutNombre) VALUES ('Eduardo Punset');
INSERT INTO lb_autores (txAutNombre) VALUES ('Edward Burman');
INSERT INTO lb_autores (txAutNombre) VALUES ('Edward Conze');
INSERT INTO lb_autores (txAutNombre) VALUES ('Elena Poniatowska');
INSERT INTO lb_autores (txAutNombre) VALUES ('Eliette Abecassis');
INSERT INTO lb_autores (txAutNombre) VALUES ('Ellis Kaut');
INSERT INTO lb_autores (txAutNombre) VALUES ('Emile Durkheim');
INSERT INTO lb_autores (txAutNombre) VALUES ('Emile Zola');
INSERT INTO lb_autores (txAutNombre) VALUES ('Emilia Pardo Bazán');
INSERT INTO lb_autores (txAutNombre) VALUES ('Emilio Sanjuán');
INSERT INTO lb_autores (txAutNombre) VALUES ('Emily Conte');
INSERT INTO lb_autores (txAutNombre) VALUES ('Emily Diamand');
INSERT INTO lb_autores (txAutNombre) VALUES ('Emmanuel Kant');
INSERT INTO lb_autores (txAutNombre) VALUES ('Enrique Cortés');
INSERT INTO lb_autores (txAutNombre) VALUES ('Enrique Gudin de la Lama');
INSERT INTO lb_autores (txAutNombre) VALUES ('Enrique Serrano');
INSERT INTO lb_autores (txAutNombre) VALUES ('Eric Frattini');
INSERT INTO lb_autores (txAutNombre) VALUES ('Erich Fromm');
INSERT INTO lb_autores (txAutNombre) VALUES ('Ernest Hemingway');
INSERT INTO lb_autores (txAutNombre) VALUES ('Ernesto Grassi');
INSERT INTO lb_autores (txAutNombre) VALUES ('Ernesto R Sábato');
INSERT INTO lb_autores (txAutNombre) VALUES ('Ernesto Sábato');
INSERT INTO lb_autores (txAutNombre) VALUES ('Esopo');
INSERT INTO lb_autores (txAutNombre) VALUES ('Esquilo');
INSERT INTO lb_autores (txAutNombre) VALUES ('Esteban Echeverría');
INSERT INTO lb_autores (txAutNombre) VALUES ('Estefanía Ferrero Marciales');
INSERT INTO lb_autores (txAutNombre) VALUES ('Estefanía Gonzaléz Vélez');
INSERT INTO lb_autores (txAutNombre) VALUES ('Eugene M. Chudnovsky');
INSERT INTO lb_autores (txAutNombre) VALUES ('Eurípides');
INSERT INTO lb_autores (txAutNombre) VALUES ('F. Scott Fitzgerald');
INSERT INTO lb_autores (txAutNombre) VALUES ('Fabio Castillo');
INSERT INTO lb_autores (txAutNombre) VALUES ('Federico Andahazi');
INSERT INTO lb_autores (txAutNombre) VALUES ('Federico Engels');
INSERT INTO lb_autores (txAutNombre) VALUES ('Fedor Dostoievski');
INSERT INTO lb_autores (txAutNombre) VALUES ('Félix María Samaniego');
INSERT INTO lb_autores (txAutNombre) VALUES ('Fernando De Rojas');
INSERT INTO lb_autores (txAutNombre) VALUES ('Fernando González');
INSERT INTO lb_autores (txAutNombre) VALUES ('Fernando Navas Talero');
INSERT INTO lb_autores (txAutNombre) VALUES ('Fernando Quiroz');
INSERT INTO lb_autores (txAutNombre) VALUES ('Fernando Savater');
INSERT INTO lb_autores (txAutNombre) VALUES ('Fernando Soto Aparicio');
INSERT INTO lb_autores (txAutNombre) VALUES ('Fiodor M. Dostoievski');
INSERT INTO lb_autores (txAutNombre) VALUES ('Flor Alba Santamaría V.');
INSERT INTO lb_autores (txAutNombre) VALUES ('Francis W. Sears');
INSERT INTO lb_autores (txAutNombre) VALUES ('Francisco de Quevedo');
INSERT INTO lb_autores (txAutNombre) VALUES ('Frank MC Court');
INSERT INTO lb_autores (txAutNombre) VALUES ('Franz Kafka');
INSERT INTO lb_autores (txAutNombre) VALUES ('Fred Reinfeld');
INSERT INTO lb_autores (txAutNombre) VALUES ('Frederic Vinyes');
INSERT INTO lb_autores (txAutNombre) VALUES ('Frederick Forsyth ');
INSERT INTO lb_autores (txAutNombre) VALUES ('Friedrich Nietzche');
INSERT INTO lb_autores (txAutNombre) VALUES ('Fulcanelli');
INSERT INTO lb_autores (txAutNombre) VALUES ('Fyodor M. Dostoevsky');
INSERT INTO lb_autores (txAutNombre) VALUES ('Gabriel García Márquez');
INSERT INTO lb_autores (txAutNombre) VALUES ('Gabriel Trujillo');
INSERT INTO lb_autores (txAutNombre) VALUES ('Gabrielle Wang');
INSERT INTO lb_autores (txAutNombre) VALUES ('Gary Jennings');
INSERT INTO lb_autores (txAutNombre) VALUES ('George H. Sabine');
INSERT INTO lb_autores (txAutNombre) VALUES ('George Orwell');
INSERT INTO lb_autores (txAutNombre) VALUES ('George Soros');
INSERT INTO lb_autores (txAutNombre) VALUES ('Georges Lefebvre');
INSERT INTO lb_autores (txAutNombre) VALUES ('Gerardo Reyes');
INSERT INTO lb_autores (txAutNombre) VALUES ('Germán Castro Caycedo');
INSERT INTO lb_autores (txAutNombre) VALUES ('German Espinosa');
INSERT INTO lb_autores (txAutNombre) VALUES ('Gianni Rodari');
INSERT INTO lb_autores (txAutNombre) VALUES ('Gilberto Rodríguez Montaña');
INSERT INTO lb_autores (txAutNombre) VALUES ('Gill Pittar');
INSERT INTO lb_autores (txAutNombre) VALUES ('Gilles Deleuze');
INSERT INTO lb_autores (txAutNombre) VALUES ('Gioconda Belli');
INSERT INTO lb_autores (txAutNombre) VALUES ('Giorgio Faletti');
INSERT INTO lb_autores (txAutNombre) VALUES ('Giovanni Papini');
INSERT INTO lb_autores (txAutNombre) VALUES ('Graham Greene');
INSERT INTO lb_autores (txAutNombre) VALUES ('Guillermo Cabrera Infante');
INSERT INTO lb_autores (txAutNombre) VALUES ('Guillermo López Acevedo');
INSERT INTO lb_autores (txAutNombre) VALUES ('Gunter Grass');
INSERT INTO lb_autores (txAutNombre) VALUES ('Gustave Flaubert');
INSERT INTO lb_autores (txAutNombre) VALUES ('Gustavo Adolfo Bécquer');
INSERT INTO lb_autores (txAutNombre) VALUES ('Gustavo Álvarez Gardeazabal');
INSERT INTO lb_autores (txAutNombre) VALUES ('Gustavo Wilches-Chaux');
INSERT INTO lb_autores (txAutNombre) VALUES ('H. G. Wells');
INSERT INTO lb_autores (txAutNombre) VALUES ('H.P. Lovecraft');
INSERT INTO lb_autores (txAutNombre) VALUES ('Hamdy A. Taha');
INSERT INTO lb_autores (txAutNombre) VALUES ('Hans Christian Andersen');
INSERT INTO lb_autores (txAutNombre) VALUES ('Hans Magnus Enzensberger');
INSERT INTO lb_autores (txAutNombre) VALUES ('Haylie Pomroy');
INSERT INTO lb_autores (txAutNombre) VALUES ('Héctor Abad Faciolince');
INSERT INTO lb_autores (txAutNombre) VALUES ('Héctor Buitrago');
INSERT INTO lb_autores (txAutNombre) VALUES ('Helí Abel Torrado');
INSERT INTO lb_autores (txAutNombre) VALUES ('Henrik Ibsen');
INSERT INTO lb_autores (txAutNombre) VALUES ('Henry Gonzalez');
INSERT INTO lb_autores (txAutNombre) VALUES ('Henry Miller');
INSERT INTO lb_autores (txAutNombre) VALUES ('Herbert Marcuse');
INSERT INTO lb_autores (txAutNombre) VALUES ('Hermann Hesse');
INSERT INTO lb_autores (txAutNombre) VALUES ('Hiromi Shinya');
INSERT INTO lb_autores (txAutNombre) VALUES ('Homero');
INSERT INTO lb_autores (txAutNombre) VALUES ('Honore De Balzac');
INSERT INTO lb_autores (txAutNombre) VALUES ('Horacio Quiroga');
INSERT INTO lb_autores (txAutNombre) VALUES ('Hugo Mancuso');
INSERT INTO lb_autores (txAutNombre) VALUES ('Ian McEwan');
INSERT INTO lb_autores (txAutNombre) VALUES ('Iliana Prieto');
INSERT INTO lb_autores (txAutNombre) VALUES ('Immanuel Kant');
INSERT INTO lb_autores (txAutNombre) VALUES ('Irene Vasco');
INSERT INTO lb_autores (txAutNombre) VALUES ('Isa Fonnegra');
INSERT INTO lb_autores (txAutNombre) VALUES ('Isaac Asimov');
INSERT INTO lb_autores (txAutNombre) VALUES ('Isabel Allende');
INSERT INTO lb_autores (txAutNombre) VALUES ('Isabel Vila');
INSERT INTO lb_autores (txAutNombre) VALUES ('Isabella Bossi Fedrigotti');
INSERT INTO lb_autores (txAutNombre) VALUES ('Italo Calvino');
INSERT INTO lb_autores (txAutNombre) VALUES ('Iván Turgueniev');
INSERT INTO lb_autores (txAutNombre) VALUES ('J. de Echano Basaldua');
INSERT INTO lb_autores (txAutNombre) VALUES ('J.D. Salinger');
INSERT INTO lb_autores (txAutNombre) VALUES ('J.K. Rowling');
INSERT INTO lb_autores (txAutNombre) VALUES ('J.R.R. Tolkien');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jack Flam');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jack London');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jackie Niebisch');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jacqueline Balcells');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jacques Aumont');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jacques Monod');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jaime Baily');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jaime Botero Gómez');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jaime Espinal');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jaime García Maffla');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jairo Aníbal Niño');
INSERT INTO lb_autores (txAutNombre) VALUES ('James A. Robinson');
INSERT INTO lb_autores (txAutNombre) VALUES ('James G. Frazer');
INSERT INTO lb_autores (txAutNombre) VALUES ('James Salter');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jane Austen');
INSERT INTO lb_autores (txAutNombre) VALUES ('Janet Lowe');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jaume Miquel Peidro');
INSERT INTO lb_autores (txAutNombre) VALUES ('Javier Cercas');
INSERT INTO lb_autores (txAutNombre) VALUES ('Javier Sierra');
INSERT INTO lb_autores (txAutNombre) VALUES ('Javier Tejada');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jay L. Devore');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jean Dominique Bauby');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jean M. Auel');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jean Piaget');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jean Rousset');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jean-Jacques Rousseau');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jean-Marie Gustave');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jeanne DuPrau');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jed Rubenfeld');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jennifer Moore-Mallinos');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jesús S. Arreola Risa');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jhon Le Carre');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jhon Steinbeck');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jim Keogh');
INSERT INTO lb_autores (txAutNombre) VALUES ('JK Rowling');
INSERT INTO lb_autores (txAutNombre) VALUES ('Joel Dicker');
INSERT INTO lb_autores (txAutNombre) VALUES ('Johan Wolfgang Von Goethe');
INSERT INTO lb_autores (txAutNombre) VALUES ('John Battelle');
INSERT INTO lb_autores (txAutNombre) VALUES ('John E. Hopcroft');
INSERT INTO lb_autores (txAutNombre) VALUES ('John Grey');
INSERT INTO lb_autores (txAutNombre) VALUES ('John Irving ');
INSERT INTO lb_autores (txAutNombre) VALUES ('John Kenneth Galbraith');
INSERT INTO lb_autores (txAutNombre) VALUES ('John P. Griffin');
INSERT INTO lb_autores (txAutNombre) VALUES ('John Stuart Mill');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jon Scieszka');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jonas Jonasson');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jorge Amado');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jorge Franco Ramos');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jorge Isaacs');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jorge Jaramillo A.');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jorge Luis Borges');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jorge Rausch');
INSERT INTO lb_autores (txAutNombre) VALUES ('José Antonio Marina');
INSERT INTO lb_autores (txAutNombre) VALUES ('José Asuncion Silva');
INSERT INTO lb_autores (txAutNombre) VALUES ('José Asunción Silva');
INSERT INTO lb_autores (txAutNombre) VALUES ('José Calles Vales');
INSERT INTO lb_autores (txAutNombre) VALUES ('José Donoso');
INSERT INTO lb_autores (txAutNombre) VALUES ('José Eustacio Rivera');
INSERT INTO lb_autores (txAutNombre) VALUES ('José Gobelo');
INSERT INTO lb_autores (txAutNombre) VALUES ('José Hernández');
INSERT INTO lb_autores (txAutNombre) VALUES ('José Luis Romero');
INSERT INTO lb_autores (txAutNombre) VALUES ('José Luis Sánchez');
INSERT INTO lb_autores (txAutNombre) VALUES ('José María Lopez Pinero');
INSERT INTO lb_autores (txAutNombre) VALUES ('José María Vargas Vila');
INSERT INTO lb_autores (txAutNombre) VALUES ('José Marroquin');
INSERT INTO lb_autores (txAutNombre) VALUES ('José Marti');
INSERT INTO lb_autores (txAutNombre) VALUES ('José Plaza');
INSERT INTO lb_autores (txAutNombre) VALUES ('José Repolles');
INSERT INTO lb_autores (txAutNombre) VALUES ('José Saramago');
INSERT INTO lb_autores (txAutNombre) VALUES ('José Zorrilla');
INSERT INTO lb_autores (txAutNombre) VALUES ('Joséph Conrad');
INSERT INTO lb_autores (txAutNombre) VALUES ('Joséph Contreras');
INSERT INTO lb_autores (txAutNombre) VALUES ('Joséph Murphy');
INSERT INTO lb_autores (txAutNombre) VALUES ('Joséph Roth');
INSERT INTO lb_autores (txAutNombre) VALUES ('Joshua Foer');
INSERT INTO lb_autores (txAutNombre) VALUES ('Jostein Gaarder');
INSERT INTO lb_autores (txAutNombre) VALUES ('Joyce Carol Oates');
INSERT INTO lb_autores (txAutNombre) VALUES ('Juan Carlos Garay');
INSERT INTO lb_autores (txAutNombre) VALUES ('Juan Carlos Onetti');
INSERT INTO lb_autores (txAutNombre) VALUES ('Juan Eslava Galán');
INSERT INTO lb_autores (txAutNombre) VALUES ('Juan Gabriel Vaquez');
INSERT INTO lb_autores (txAutNombre) VALUES ('Juan Goytisolo');
INSERT INTO lb_autores (txAutNombre) VALUES ('Juan Gustavo Cobo Borda');
INSERT INTO lb_autores (txAutNombre) VALUES ('Juan José Benitez');
INSERT INTO lb_autores (txAutNombre) VALUES ('Juan Marse');
INSERT INTO lb_autores (txAutNombre) VALUES ('Juan Pablo Escobar');
INSERT INTO lb_autores (txAutNombre) VALUES ('Juan Ramon Jimenez');
INSERT INTO lb_autores (txAutNombre) VALUES ('Juan Rousseau');
INSERT INTO lb_autores (txAutNombre) VALUES ('Juan Rufo');
INSERT INTO lb_autores (txAutNombre) VALUES ('Juan Rulfo');
INSERT INTO lb_autores (txAutNombre) VALUES ('Judith Kerr');
INSERT INTO lb_autores (txAutNombre) VALUES ('Julia Mercedes Castilla');
INSERT INTO lb_autores (txAutNombre) VALUES ('Julio Cortázar');
INSERT INTO lb_autores (txAutNombre) VALUES ('Julio Verna');
INSERT INTO lb_autores (txAutNombre) VALUES ('K.L. Keller');
INSERT INTO lb_autores (txAutNombre) VALUES ('Karen Blixen (Isak Dinesen)');
INSERT INTO lb_autores (txAutNombre) VALUES ('Karl Marx');
INSERT INTO lb_autores (txAutNombre) VALUES ('Katja Held');
INSERT INTO lb_autores (txAutNombre) VALUES ('Keiko Kasza');
INSERT INTO lb_autores (txAutNombre) VALUES ('Ken Follet');
INSERT INTO lb_autores (txAutNombre) VALUES ('Kitty Kelley');
INSERT INTO lb_autores (txAutNombre) VALUES ('Langenscheidt');
INSERT INTO lb_autores (txAutNombre) VALUES ('Laura esquivel');
INSERT INTO lb_autores (txAutNombre) VALUES ('Laura Lemay');
INSERT INTO lb_autores (txAutNombre) VALUES ('Laura Restrepo');
INSERT INTO lb_autores (txAutNombre) VALUES ('Laura Sesana');
INSERT INTO lb_autores (txAutNombre) VALUES ('Le Clezio');
INSERT INTO lb_autores (txAutNombre) VALUES ('Leibniz');
INSERT INTO lb_autores (txAutNombre) VALUES ('Leo Perutz');
INSERT INTO lb_autores (txAutNombre) VALUES ('Leon Chaitow');
INSERT INTO lb_autores (txAutNombre) VALUES ('León Tolstoi');
INSERT INTO lb_autores (txAutNombre) VALUES ('Leonardo Sciascia');
INSERT INTO lb_autores (txAutNombre) VALUES ('Leonor Cabeza de Vergara');
INSERT INTO lb_autores (txAutNombre) VALUES ('Lewis Carroll');
INSERT INTO lb_autores (txAutNombre) VALUES ('Lilia Lardone');
INSERT INTO lb_autores (txAutNombre) VALUES ('Liliana Bodoc');
INSERT INTO lb_autores (txAutNombre) VALUES ('Liu Si-yuan');
INSERT INTO lb_autores (txAutNombre) VALUES ('Longo');
INSERT INTO lb_autores (txAutNombre) VALUES ('Lorna Byrne');
INSERT INTO lb_autores (txAutNombre) VALUES ('Louis Leithold');
INSERT INTO lb_autores (txAutNombre) VALUES ('Lucy Hawking ');
INSERT INTO lb_autores (txAutNombre) VALUES ('Luis Fayad');
INSERT INTO lb_autores (txAutNombre) VALUES ('Luis Joyanes Aguilar');
INSERT INTO lb_autores (txAutNombre) VALUES ('Luis Vargas Tejada');
INSERT INTO lb_autores (txAutNombre) VALUES ('Luz Mary Giraldo');
INSERT INTO lb_autores (txAutNombre) VALUES ('Lygia Bojunga');
INSERT INTO lb_autores (txAutNombre) VALUES ('M. Kant');
INSERT INTO lb_autores (txAutNombre) VALUES ('M. Lobosco');
INSERT INTO lb_autores (txAutNombre) VALUES ('M.D. Spencer Johnson');
INSERT INTO lb_autores (txAutNombre) VALUES ('M.I. Mijailov');
INSERT INTO lb_autores (txAutNombre) VALUES ('Manuel A. Carreno');
INSERT INTO lb_autores (txAutNombre) VALUES ('Manuel Mejia Vallejo');
INSERT INTO lb_autores (txAutNombre) VALUES ('Manuel Rivas');
INSERT INTO lb_autores (txAutNombre) VALUES ('Marce Birmajer');
INSERT INTO lb_autores (txAutNombre) VALUES ('Marcela Serrano');
INSERT INTO lb_autores (txAutNombre) VALUES ('Marcelo Birmajer');
INSERT INTO lb_autores (txAutNombre) VALUES ('Marcia Grad');
INSERT INTO lb_autores (txAutNombre) VALUES ('Marcial');
INSERT INTO lb_autores (txAutNombre) VALUES ('Margaret Atwood');
INSERT INTO lb_autores (txAutNombre) VALUES ('Margaret Mitchell');
INSERT INTO lb_autores (txAutNombre) VALUES ('Marguerite Yourcenar');
INSERT INTO lb_autores (txAutNombre) VALUES ('María Baranda');
INSERT INTO lb_autores (txAutNombre) VALUES ('María del Pilar García G');
INSERT INTO lb_autores (txAutNombre) VALUES ('María Idalia Gomez');
INSERT INTO lb_autores (txAutNombre) VALUES ('María Jimena Duzán');
INSERT INTO lb_autores (txAutNombre) VALUES ('María José Martínez');
INSERT INTO lb_autores (txAutNombre) VALUES ('María Villegas');
INSERT INTO lb_autores (txAutNombre) VALUES ('Mario Aguilera Peña');
INSERT INTO lb_autores (txAutNombre) VALUES ('Mario Benedetti');
INSERT INTO lb_autores (txAutNombre) VALUES ('Mario Mendoza');
INSERT INTO lb_autores (txAutNombre) VALUES ('Mario Puzo');
INSERT INTO lb_autores (txAutNombre) VALUES ('Mario Vargas Llosa');
INSERT INTO lb_autores (txAutNombre) VALUES ('Mark Twain');
INSERT INTO lb_autores (txAutNombre) VALUES ('Marta Diaz Pineroba');
INSERT INTO lb_autores (txAutNombre) VALUES ('Martha Helena Barreto R.');
INSERT INTO lb_autores (txAutNombre) VALUES ('Marx Weber');
INSERT INTO lb_autores (txAutNombre) VALUES ('Mary Bowen');
INSERT INTO lb_autores (txAutNombre) VALUES ('Mary Higgins Clark');
INSERT INTO lb_autores (txAutNombre) VALUES ('Mary Higgins Clark ');
INSERT INTO lb_autores (txAutNombre) VALUES ('Matthew Pearl');
INSERT INTO lb_autores (txAutNombre) VALUES ('Maurice Druon');
INSERT INTO lb_autores (txAutNombre) VALUES ('Maurice Duverger');
INSERT INTO lb_autores (txAutNombre) VALUES ('Maurice Leblanc');
INSERT INTO lb_autores (txAutNombre) VALUES ('max gallo');
INSERT INTO lb_autores (txAutNombre) VALUES ('Maxime Chevalier');
INSERT INTO lb_autores (txAutNombre) VALUES ('Michael E. Porter');
INSERT INTO lb_autores (txAutNombre) VALUES ('Michael Joséph Miller');
INSERT INTO lb_autores (txAutNombre) VALUES ('Michel Eyquen de Montaigne');
INSERT INTO lb_autores (txAutNombre) VALUES ('Miguel Angel Cornejo');
INSERT INTO lb_autores (txAutNombre) VALUES ('Miguel de Cervantes Saavedra');
INSERT INTO lb_autores (txAutNombre) VALUES ('Milan Kundera');
INSERT INTO lb_autores (txAutNombre) VALUES ('Milewski Harford');
INSERT INTO lb_autores (txAutNombre) VALUES ('Mircea Eliade');
INSERT INTO lb_autores (txAutNombre) VALUES ('Mirjam Pressler and Anaya');
INSERT INTO lb_autores (txAutNombre) VALUES ('Moliére');
INSERT INTO lb_autores (txAutNombre) VALUES ('Morris Rosenthal');
INSERT INTO lb_autores (txAutNombre) VALUES ('Munro Alice');
INSERT INTO lb_autores (txAutNombre) VALUES ('Murray Cooper');
INSERT INTO lb_autores (txAutNombre) VALUES ('Myriam Stella Aponte Báez');
INSERT INTO lb_autores (txAutNombre) VALUES ('Nelson Mandela');
INSERT INTO lb_autores (txAutNombre) VALUES ('Nicholas Abercrombie');
INSERT INTO lb_autores (txAutNombre) VALUES ('Nicholas Carr');
INSERT INTO lb_autores (txAutNombre) VALUES ('Nicole C. Vasseler');
INSERT INTO lb_autores (txAutNombre) VALUES ('Nicos Poulantzas');
INSERT INTO lb_autores (txAutNombre) VALUES ('Octavio Paz');
INSERT INTO lb_autores (txAutNombre) VALUES ('Og Mandino');
INSERT INTO lb_autores (txAutNombre) VALUES ('Orhan Pamuk');
INSERT INTO lb_autores (txAutNombre) VALUES ('Orián Jiménez Meneses');
INSERT INTO lb_autores (txAutNombre) VALUES ('Oriana Fallaci');
INSERT INTO lb_autores (txAutNombre) VALUES ('Oscar Collazos');
INSERT INTO lb_autores (txAutNombre) VALUES ('Oscar Wilde');
INSERT INTO lb_autores (txAutNombre) VALUES ('Osvaldo Vladimir Maraboli Salazar');
INSERT INTO lb_autores (txAutNombre) VALUES ('Pablo De Santis');
INSERT INTO lb_autores (txAutNombre) VALUES ('Pablo Neruda');
INSERT INTO lb_autores (txAutNombre) VALUES ('Paco Ignacio Taibo II');
INSERT INTO lb_autores (txAutNombre) VALUES ('Patrice Boussel');
INSERT INTO lb_autores (txAutNombre) VALUES ('Patricia Lara Salive');
INSERT INTO lb_autores (txAutNombre) VALUES ('Patricia Urzua May ');
INSERT INTO lb_autores (txAutNombre) VALUES ('Patrick Suskind');
INSERT INTO lb_autores (txAutNombre) VALUES ('Paul A. Tipler');
INSERT INTO lb_autores (txAutNombre) VALUES ('Paul Dorsey');
INSERT INTO lb_autores (txAutNombre) VALUES ('Paul Poupard');
INSERT INTO lb_autores (txAutNombre) VALUES ('Paula Bombara');
INSERT INTO lb_autores (txAutNombre) VALUES ('Paula Hawkins');
INSERT INTO lb_autores (txAutNombre) VALUES ('Paulo Afonso Lopes');
INSERT INTO lb_autores (txAutNombre) VALUES ('Paulo Coelho');
INSERT INTO lb_autores (txAutNombre) VALUES ('Paulo Cohelo');
INSERT INTO lb_autores (txAutNombre) VALUES ('Pedro Gomez Valderrama');
INSERT INTO lb_autores (txAutNombre) VALUES ('Pedro Salinas');
INSERT INTO lb_autores (txAutNombre) VALUES ('Pertti Karkainen');
INSERT INTO lb_autores (txAutNombre) VALUES ('Petrit Baquero');
INSERT INTO lb_autores (txAutNombre) VALUES ('Philippe Claudel');
INSERT INTO lb_autores (txAutNombre) VALUES ('Platón');
INSERT INTO lb_autores (txAutNombre) VALUES ('Plutarco');
INSERT INTO lb_autores (txAutNombre) VALUES ('Prahalad');
INSERT INTO lb_autores (txAutNombre) VALUES ('Primo Levi');
INSERT INTO lb_autores (txAutNombre) VALUES ('R.L. Stevenson');
INSERT INTO lb_autores (txAutNombre) VALUES ('Rafael Alberti');
INSERT INTO lb_autores (txAutNombre) VALUES ('Rafael Chaparro');
INSERT INTO lb_autores (txAutNombre) VALUES ('Ramón García Domínguez ');
INSERT INTO lb_autores (txAutNombre) VALUES ('Ramon Gomez de la Serna');
INSERT INTO lb_autores (txAutNombre) VALUES ('Raymond A. Serway');
INSERT INTO lb_autores (txAutNombre) VALUES ('René Descartes');
INSERT INTO lb_autores (txAutNombre) VALUES ('Ricardo Alcantara');
INSERT INTO lb_autores (txAutNombre) VALUES ('Ricardo Piglia');
INSERT INTO lb_autores (txAutNombre) VALUES ('Ricardo Silva');
INSERT INTO lb_autores (txAutNombre) VALUES ('Richard Bach');
INSERT INTO lb_autores (txAutNombre) VALUES ('Richard Johnsonbaugh');
INSERT INTO lb_autores (txAutNombre) VALUES ('Roald Dahl');
INSERT INTO lb_autores (txAutNombre) VALUES ('Robert A. Manners');
INSERT INTO lb_autores (txAutNombre) VALUES ('Robert Fisher');
INSERT INTO lb_autores (txAutNombre) VALUES ('Robert Louis Stevenson');
INSERT INTO lb_autores (txAutNombre) VALUES ('Roberto Ampuero');
INSERT INTO lb_autores (txAutNombre) VALUES ('Robin Norwood');
INSERT INTO lb_autores (txAutNombre) VALUES ('Robin S. Sharma');
INSERT INTO lb_autores (txAutNombre) VALUES ('Rocio Londoño Peñaranda');
INSERT INTO lb_autores (txAutNombre) VALUES ('Roger Penrose');
INSERT INTO lb_autores (txAutNombre) VALUES ('Roger S. Pressman');
INSERT INTO lb_autores (txAutNombre) VALUES ('Rogers Cadenhead');
INSERT INTO lb_autores (txAutNombre) VALUES ('Roland E. Larson');
INSERT INTO lb_autores (txAutNombre) VALUES ('Ronald E. Walpole');
INSERT INTO lb_autores (txAutNombre) VALUES ('Rosa Navarro Durán');
INSERT INTO lb_autores (txAutNombre) VALUES ('Rosemary Sutcliff');
INSERT INTO lb_autores (txAutNombre) VALUES ('Salman Rushdie');
INSERT INTO lb_autores (txAutNombre) VALUES ('Samuel Benchetrit');
INSERT INTO lb_autores (txAutNombre) VALUES ('Sandor Marai');
INSERT INTO lb_autores (txAutNombre) VALUES ('Santiago Gamboa');
INSERT INTO lb_autores (txAutNombre) VALUES ('Santiago Rojas Posada');
INSERT INTO lb_autores (txAutNombre) VALUES ('Santo Tomás');
INSERT INTO lb_autores (txAutNombre) VALUES ('Sascha Barboza');
INSERT INTO lb_autores (txAutNombre) VALUES ('Scott Urman');
INSERT INTO lb_autores (txAutNombre) VALUES ('Sebastián Saldarriaga');
INSERT INTO lb_autores (txAutNombre) VALUES ('Sharon Creech');
INSERT INTO lb_autores (txAutNombre) VALUES ('Sherry Argov');
INSERT INTO lb_autores (txAutNombre) VALUES ('Sid Fleischman');
INSERT INTO lb_autores (txAutNombre) VALUES ('Sigmund Freud');
INSERT INTO lb_autores (txAutNombre) VALUES ('Silvia miguens');
INSERT INTO lb_autores (txAutNombre) VALUES ('Sin especificar');
INSERT INTO lb_autores (txAutNombre) VALUES ('Slavenka Drakulic');
INSERT INTO lb_autores (txAutNombre) VALUES ('Sófocles');
INSERT INTO lb_autores (txAutNombre) VALUES ('Soledad Puertolas');
INSERT INTO lb_autores (txAutNombre) VALUES ('Soren Kierkegaard');
INSERT INTO lb_autores (txAutNombre) VALUES ('Stendhal');
INSERT INTO lb_autores (txAutNombre) VALUES ('Stephen King');
INSERT INTO lb_autores (txAutNombre) VALUES ('Stephen R. Covey');
INSERT INTO lb_autores (txAutNombre) VALUES ('Stephen W. Hawking');
INSERT INTO lb_autores (txAutNombre) VALUES ('Stephenie Meyer');
INSERT INTO lb_autores (txAutNombre) VALUES ('Stieg Larsson');
INSERT INTO lb_autores (txAutNombre) VALUES ('Susan Sontag');
INSERT INTO lb_autores (txAutNombre) VALUES ('T.S. Kuhn');
INSERT INTO lb_autores (txAutNombre) VALUES ('Terence Blacker');
INSERT INTO lb_autores (txAutNombre) VALUES ('Thomas Bulfinch');
INSERT INTO lb_autores (txAutNombre) VALUES ('Thomas M. Connolly');
INSERT INTO lb_autores (txAutNombre) VALUES ('Tom Holland ');
INSERT INTO lb_autores (txAutNombre) VALUES ('Tomás Carrasquilla');
INSERT INTO lb_autores (txAutNombre) VALUES ('Tomás de Iriarte');
INSERT INTO lb_autores (txAutNombre) VALUES ('Tomás González');
INSERT INTO lb_autores (txAutNombre) VALUES ('Tonya Hurley');
INSERT INTO lb_autores (txAutNombre) VALUES ('Tor Andrae');
INSERT INTO lb_autores (txAutNombre) VALUES ('Truman Capote');
INSERT INTO lb_autores (txAutNombre) VALUES ('Valerio Manfredi');
INSERT INTO lb_autores (txAutNombre) VALUES ('Vegetta777');
INSERT INTO lb_autores (txAutNombre) VALUES ('Vicente Muñoz Puelles');
INSERT INTO lb_autores (txAutNombre) VALUES ('Victor E. Frankl');
INSERT INTO lb_autores (txAutNombre) VALUES ('Víctor Hugo');
INSERT INTO lb_autores (txAutNombre) VALUES ('Virgil');
INSERT INTO lb_autores (txAutNombre) VALUES ('Virginia Woolf');
INSERT INTO lb_autores (txAutNombre) VALUES ('Vivek Gupta');
INSERT INTO lb_autores (txAutNombre) VALUES ('VLADDO');
INSERT INTO lb_autores (txAutNombre) VALUES ('Vladimir Nabokov');
INSERT INTO lb_autores (txAutNombre) VALUES ('W. Bennis');
INSERT INTO lb_autores (txAutNombre) VALUES ('W. Ebernstein');
INSERT INTO lb_autores (txAutNombre) VALUES ('Walter Montenegro');
INSERT INTO lb_autores (txAutNombre) VALUES ('Walter Riso');
INSERT INTO lb_autores (txAutNombre) VALUES ('Washington Irving');
INSERT INTO lb_autores (txAutNombre) VALUES ('Wassily Kandinsky');
INSERT INTO lb_autores (txAutNombre) VALUES ('Wilkie Collins');
INSERT INTO lb_autores (txAutNombre) VALUES ('William Burroughs');
INSERT INTO lb_autores (txAutNombre) VALUES ('William Faulkner');
INSERT INTO lb_autores (txAutNombre) VALUES ('William Golding');
INSERT INTO lb_autores (txAutNombre) VALUES ('William Landay');
INSERT INTO lb_autores (txAutNombre) VALUES ('William ospina');
INSERT INTO lb_autores (txAutNombre) VALUES ('William Ospina ');
INSERT INTO lb_autores (txAutNombre) VALUES ('William Shakespeare');
INSERT INTO lb_autores (txAutNombre) VALUES ('William Stallings');
INSERT INTO lb_autores (txAutNombre) VALUES ('Winfried Karl Grassmann');
INSERT INTO lb_autores (txAutNombre) VALUES ('Yolanda Reyes');
INSERT INTO lb_autores (txAutNombre) VALUES ('Yukio Mishima');
INSERT INTO lb_autores (txAutNombre) VALUES ('Zoe Sallis');
commit;
commit;commit;
commit;commit;
commit;commit;
