SELECT * FROM dotex4read.lb_generos;

delete FROM dotex4read.lb_generos where ingenero > 0;
alter table dotEx4read.lb_generos auto_increment=1;
commit;
commit;commit;
commit;commit;
commit;commit;
commit;

INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Académico');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Antología');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Arte y cultura');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Autoayuda');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Autobiografía');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Bienestar');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Biografía');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Ciencia ficción');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Ciencias Naturales');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Ciencias Sociales');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Científico');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Cocina');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Comercio y negocios');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Crónica');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Cuentos');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Cuentos cortos');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Cuentos infantiles');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Drama');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Economía');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Enciclopedias');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Ensayo');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Esóterico');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Espiritualidad');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Exito');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Fabula empresarial');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Ficción');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Filosofía');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Finanzas');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Física');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Gerencia y liderazgo');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Guía');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Historia');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Home');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Humor');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Humor Político');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Ingeniería');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Inglés');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Investigación');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Literatura');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Literatura Fantástica');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Literatura infantil');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Literatura Inglesa');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Literatura juvenil');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Literatura Latinoamericana');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Literatura Universal');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Matemáticas');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Matemáticas Universitarias');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Medicina');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Memorias');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Metodología');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Motivación');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Novela');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Novela corta');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Novela de aventuras');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Novela de desarrollo');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Novela fantástica');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Novela Griega');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Novela juvenil');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Novela Negra');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Novela Romántica');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Pedagogía');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Pensamiento');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Plan lector');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Poesía');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Poesía Erótica');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Poesía hispanoamericana');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Política');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Publicidad y mercadeo');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Salud');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Salud y Bienestar');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Sin especificar');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Superación');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Teatro');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Técnica Actuación');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Tecnología e Informática');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Terror');
INSERT INTO `lb_generos`(`txGenNombre`)VALUES('Veterinaria, Zootecnia');

commit;
commit;commit;
commit;commit;
commit;commit;
