## 0. Pendientes
##  - crerar una tabla de direcciones y teléfonos de contacto?
##  - cargar o permitir una imágen de usuario
##  - cargar fecha de nacimiento para los que tienen
##  - EL TEXTO DE VALIDACION DEL REGISTRO???
##  - Para la clave, debo usar la misma para todos y cambiarla...debe ser como la inicial de ex4read de nuevo, debo sacarlo de mailchimp

## 1. Crear lb_planesusuarios
## 2. Crear lb_usuarios
 

delete FROM dotex4read.lb_actsesion where inactsesion > 0;
delete FROM dotex4read.lb_sesiones where insesion > 0;
delete FROM dotex4read.lb_dispusuarios where indispusuario > 0;
delete FROM dotex4read.lb_membresias where inmembresia > 0;
delete FROM dotex4read.lb_usuarios where inusuario > 0;

alter table dotEx4read.lb_actsesion  auto_increment=1;
alter table dotEx4read.lb_sesiones  auto_increment=1;
alter table dotEx4read.lb_dispusuarios  auto_increment=1;
alter table dotEx4read.lb_membresias  auto_increment=1;
alter table dotEx4read.lb_usuarios  auto_increment=1;

INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(1, 'alexviatela@gmail.com', 'alexviatela@gmail.com', 'Manuel Ramirez', 'Manuel Ramirez', 0, 5, 'Manuel', 1, 'PENDIENTE', '2016-4-4 18:46', '2016-7-22 14:13');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(1, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(2, 'luzacifuentes@gmail.com', 'luzacifuentes@gmail.com', 'Luz Adriana Cifuentes Caballero', 'Luz Adriana Cifuentes Caballero', 1, 5, 'Luz Adriana', 1, 'PENDIENTE', '2016-4-5 18:46', '2016-7-23 14:13');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(2, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(3, 'ramvia@gmail.com', 'ramvia@gmail.com', 'Luis Carlos Ramirez Viatela', 'Luis Carlos Ramirez Viatela', 0, 5, 'Luis Carlos', 1, 'PENDIENTE', '2016-4-6 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(3, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(4, 'fabian.heredia@gmail.com', 'fabian.heredia@gmail.com', 'Fabian Camilo Heredia Rodríguez', 'Fabian Camilo Heredia Rodríguez', 0, 5, 'Fabian Camilo', 1, 'PENDIENTE', '2016-4-7 18:46', '2016-4-20 11:19');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(4, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(5, 'xfuentesbaicue@gmail.com', 'xfuentesbaicue@gmail.com', 'Ximena Fuentes', 'Ximena Fuentes', 1, 5, 'Ximena', 1, 'PENDIENTE', '2016-4-8 18:46', '2016-5-2 10:45');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(5, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(6, 'javierparkour@gmail.com', 'javierparkour@gmail.com', 'Javier Escudero', 'Javier Escudero', 0, 5, 'Javier', 1, 'PENDIENTE', '2016-4-9 18:46', '2016-4-20 11:25');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(6, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(7, 'ingwilsonher@gmail.com', 'ingwilsonher@gmail.com', 'Wilson Hernandez', 'Wilson Hernandez', 0, 5, 'Wilson', 1, 'PENDIENTE', '2016-4-10 18:46', '2016-4-20 11:27');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(7, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(8, 'nabr.04@gmail.com', 'nabr.04@gmail.com', 'Natalia Andrea Borbon', 'Natalia Andrea Borbon', 1, 5, 'Natalia Andrea', 1, 'PENDIENTE', '2016-4-11 18:46', '2016-4-26 13:49');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(8, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(9, 'angela_rodr@hotmail.com', 'angela_rodr@hotmail.com', 'Angela Daiana Rodriguez Puerto', 'Angela Daiana Rodriguez Puerto', 1, 5, 'Angela Daiana', 1, 'PENDIENTE', '2016-4-12 18:46', '2016-6-15 16:24');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(9, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(10, 'putomelodrama@gmail.com', 'putomelodrama@gmail.com', 'Luisa Rojas', 'Luisa Rojas', 1, 5, 'Luisa', 1, 'PENDIENTE', '2016-4-13 18:46', '2016-6-17 18:24');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(10, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(11, 'segalindoa@gmail.com', 'segalindoa@gmail.com', 'Sergio Galindo', 'Sergio Galindo', 0, 5, 'Sergio', 1, 'PENDIENTE', '2016-4-14 18:46', '2016-4-20 11:34');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(11, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(12, 'manuel.daza90@gmail.com', 'manuel.daza90@gmail.com', 'Manuel Alejandro Daza', 'Manuel Alejandro Daza', 0, 5, 'Manuel Alejandro', 1, 'PENDIENTE', '2016-4-15 18:46', '2016-4-20 11:37');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(12, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(13, 'lml-Ivan@hotmail.com', 'lml-Ivan@hotmail.com', 'Iván Patiño', 'Iván Patiño', 0, 5, 'Iván', 1, 'PENDIENTE', '2016-4-16 18:46', '2016-4-20 11:37');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(13, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(14, 'afortiz34@misena.edu.co', 'afortiz34@misena.edu.co', 'Andres Ortiz Rosario', 'Andres Ortiz Rosario', 0, 5, 'Andres', 1, 'PENDIENTE', '2016-4-17 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(14, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(15, 'danielfduenas@gmail.com', 'danielfduenas@gmail.com', 'Daniel Dueñas', 'Daniel Dueñas', 0, 5, 'Daniel', 1, 'PENDIENTE', '2016-4-18 18:46', '2016-4-20 20:42');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(15, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(16, 'estebangaleano5@hotmail.com', 'estebangaleano5@hotmail.com', 'Esteban Galeano', 'Esteban Galeano', 0, 5, 'Esteban', 1, 'PENDIENTE', '2016-4-19 18:46', '2016-5-31 19:13');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(16, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(17, 'bebecauac@gmail.com', 'bebecauac@gmail.com', 'Diana Gómez', 'Diana Gómez', 1, 5, 'Diana', 1, 'PENDIENTE', '2016-4-20 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(17, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(18, 'lauraquinche7@gmail.com', 'lauraquinche7@gmail.com', 'Laura Quinche', 'Laura Quinche', 1, 5, 'Laura', 1, 'PENDIENTE', '2016-4-21 18:46', '2016-4-26 20:2');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(18, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(19, 'pereajas@gmail.com', 'pereajas@gmail.com', 'Jasmith .', 'Jasmith .', 1, 5, 'Jasmith', 1, 'PENDIENTE', '2016-4-22 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(19, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(20, 'anvapal_10@hotmail.com', 'anvapal_10@hotmail.com', 'Angie  Palacios', 'Angie  Palacios', 1, 5, 'Angie ', 1, 'PENDIENTE', '2016-4-23 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(20, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(21, 'davidsantiagogc@gmail.com', 'davidsantiagogc@gmail.com', 'David Santiago .', 'David Santiago .', 0, 5, 'David Santiago', 1, 'PENDIENTE', '2016-4-24 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(21, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(22, 'Selectorporto@gmail.com', 'Selectorporto@gmail.com', 'Raul Lopez', 'Raul Lopez', 0, 5, 'Raul', 1, 'PENDIENTE', '2016-4-25 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(22, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(23, 'jdtorres9611@gmail.com', 'jdtorres9611@gmail.com', 'Juan David Torres', 'Juan David Torres', 0, 5, 'Juan David', 1, 'PENDIENTE', '2016-4-26 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(23, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(24, 'asfer77@hotmail.com', 'asfer77@hotmail.com', 'Luisa Fernanda Arias Fernández', 'Luisa Fernanda Arias Fernández', 1, 5, 'Luisa Fernanda', 1, 'PENDIENTE', '2016-4-27 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(24, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(25, 'Oskarfuentes001@gmail.com', 'Oskarfuentes001@gmail.com', 'Oscar Fuentes Achury', 'Oscar Fuentes Achury', 0, 5, 'Oscar', 1, 'PENDIENTE', '2016-4-28 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(25, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(26, 'cony.velazco@hotmail.com', 'cony.velazco@hotmail.com', 'Cony Velazco', 'Cony Velazco', 1, 5, 'Cony', 1, 'PENDIENTE', '2016-4-29 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(26, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(27, 'dgomez001@gmail.com', 'dgomez001@gmail.com', 'Doris Cecilia Gómez Camargo', 'Doris Cecilia Gómez Camargo', 1, 5, 'Doris Cecilia', 1, 'PENDIENTE', '2016-4-30 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(27, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(28, 'sonoroguillermo@hotmail.com', 'sonoroguillermo@hotmail.com', 'Guillermo  Muñoz', 'Guillermo  Muñoz', 0, 5, 'Guillermo ', 1, 'PENDIENTE', '2016-5-1 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(28, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(29, 'algil23@yahoo.es', 'algil23@yahoo.es', 'Alba Luz Gil', 'Alba Luz Gil', 1, 5, 'Alba Luz', 1, 'PENDIENTE', '2016-5-2 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(29, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(30, 'gutimoreno@yahoo.com', 'gutimoreno@yahoo.com', 'Elka Gutierrez', 'Elka Gutierrez', 1, 5, 'Elka', 1, 'PENDIENTE', '2016-5-3 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(30, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(31, 'Andmur.56@gmail.com', 'Andmur.56@gmail.com', 'Anderson Murillo', 'Anderson Murillo', 0, 5, 'Anderson', 1, 'PENDIENTE', '2016-5-4 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(31, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(32, 'izquiwrde@hotmail.com', 'izquiwrde@hotmail.com', 'Ruth Alfonso', 'Ruth Alfonso', 1, 5, 'Ruth', 1, 'PENDIENTE', '2016-5-5 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(32, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(33, 'izquuwrde@hotmail.com', 'izquuwrde@hotmail.com', 'Ruth Alfonso', 'Ruth Alfonso', 1, 5, 'Ruth', 1, 'PENDIENTE', '2016-5-6 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(33, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(34, 'duramarsaluna96@hotmail.com', 'duramarsaluna96@hotmail.com', 'Marcela Moreno Guzman', 'Marcela Moreno Guzman', 1, 5, 'Marcela', 1, 'PENDIENTE', '2016-5-7 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(34, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(35, 'gpso60@hotmail.com', 'gpso60@hotmail.com', 'Gloria Patricia Sanchez Ortega ', 'Gloria Patricia Sanchez Ortega ', 1, 5, 'Gloria Patricia', 1, 'PENDIENTE', '2016-5-8 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(35, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(36, 'ivanramiro97@gmail.com', 'ivanramiro97@gmail.com', 'Iván .', 'Iván .', 0, 5, 'Iván', 1, 'PENDIENTE', '2016-5-9 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(36, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(37, 'ahenrytoh@hotmail.com', 'ahenrytoh@hotmail.com', 'Henry .', 'Henry .', 0, 5, 'Henry', 1, 'PENDIENTE', '2016-5-10 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(37, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(38, 'Yduy47@hotmail.com', 'Yduy47@hotmail.com', 'Yudy G Duarte Prieto', 'Yudy G Duarte Prieto', 1, 5, 'Yudy G', 1, 'PENDIENTE', '2016-5-11 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(38, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(39, 'fcho667@hotmail.com', 'fcho667@hotmail.com', 'Cesar Fernando Cifuentes', 'Cesar Fernando Cifuentes', 0, 5, 'Cesar Fernando', 1, 'PENDIENTE', '2016-5-12 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(39, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(40, 'lupaenca@gmail.com', 'lupaenca@gmail.com', 'Carolina Benavides', 'Carolina Benavides', 1, 5, 'Carolina', 1, 'PENDIENTE', '2016-5-13 18:46', '2016-5-27 8:1');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(40, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(41, 'luracal@hotmail.com', 'luracal@hotmail.com', 'Luis Cardenas', 'Luis Cardenas', 0, 5, 'Luis', 1, 'PENDIENTE', '2016-5-14 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(41, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(42, 'mariaplaza902@gmail.com', 'mariaplaza902@gmail.com', 'Maria Plaza', 'Maria Plaza', 1, 5, 'Maria', 1, 'PENDIENTE', '2016-5-15 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(42, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(43, 'dianamorjuelar@gmail.com', 'dianamorjuelar@gmail.com', 'Diana Marcela Orjuela', 'Diana Marcela Orjuela', 1, 5, 'Diana Marcela', 1, 'PENDIENTE', '2016-5-16 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(43, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(44, 'marengoar@gmail.com', 'marengoar@gmail.com', 'Martha Gómez', 'Martha Gómez', 1, 5, 'Martha', 1, 'PENDIENTE', '2016-5-17 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(44, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(45, 'leidyk18@hotmail.com', 'leidyk18@hotmail.com', 'Leidy Sabogal', 'Leidy Sabogal', 1, 5, 'Leidy', 1, 'PENDIENTE', '2016-5-18 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(45, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(46, 'hbellog@gmail.com', 'hbellog@gmail.com', 'Adolfo .', 'Adolfo .', 1, 5, 'Adolfo', 1, 'PENDIENTE', '2016-5-19 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(46, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(47, 'villamizarnegocios@hotmail.com', 'villamizarnegocios@hotmail.com', 'Diego Villamizar', 'Diego Villamizar', 0, 5, 'Diego', 1, 'PENDIENTE', '2016-5-20 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(47, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(48, 'lumarcar2006@yahoo.es', 'lumarcar2006@yahoo.es', 'Luis Martín Carreño', 'Luis Martín Carreño', 0, 5, 'Luis Martín', 1, 'PENDIENTE', '2016-5-21 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(48, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(49, 'luisalunar22@hotmail.com', 'luisalunar22@hotmail.com', 'Luisa Useche', 'Luisa Useche', 1, 5, 'Luisa', 1, 'PENDIENTE', '2016-5-22 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(49, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(50, 'Maryury_131@hotmail.com', 'Maryury_131@hotmail.com', 'Wendy Parra', 'Wendy Parra', 1, 5, 'Wendy', 1, 'PENDIENTE', '2016-5-23 18:46', '2016-5-4 8:58');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(50, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(51, 'arfzelaya@gmail.com', 'arfzelaya@gmail.com', 'Alberto Zelaya', 'Alberto Zelaya', 0, 5, 'Alberto', 1, 'PENDIENTE', '2016-5-24 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(51, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(52, 'vmslatino@yahoo.com', 'vmslatino@yahoo.com', 'Victor Sandoval', 'Victor Sandoval', 0, 5, 'Victor', 1, 'PENDIENTE', '2016-5-25 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(52, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(53, 'Leorock851@gmail.com', 'Leorock851@gmail.com', 'Leonardo .', 'Leonardo .', 1, 5, 'Leonardo', 1, 'PENDIENTE', '2016-5-26 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(53, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(54, 'lorsy.constanza.torres@gmail.com', 'lorsy.constanza.torres@gmail.com', 'Lorsi Constanza Torres Ramirez', 'Lorsi Constanza Torres Ramirez', 1, 5, 'Lorsi Constanza', 1, 'PENDIENTE', '2016-5-27 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(54, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(55, 'Nancycoduran@gmail.com', 'Nancycoduran@gmail.com', 'Nancy Duran', 'Nancy Duran', 1, 5, 'Nancy', 1, 'PENDIENTE', '2016-5-28 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(55, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(56, 'sebastiancifuentes_15@hotmail.com', 'sebastiancifuentes_15@hotmail.com', 'John Sebastian Cifuentes', 'John Sebastian Cifuentes', 0, 5, 'John Sebastian', 1, 'PENDIENTE', '2016-5-29 18:46', '2016-8-2 18:29');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(56, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(57, 'yalet.libros@gmail.com', 'yalet.libros@gmail.com', 'Alexander Herrera', 'Alexander Herrera', 0, 5, 'Alexander', 1, 'PENDIENTE', '2016-5-30 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(57, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(58, 'bgarciaderojas@yahoo.com', 'bgarciaderojas@yahoo.com', 'Beatríz García de Rojas', 'Beatríz García de Rojas', 1, 5, 'Beatríz', 1, 'PENDIENTE', '2016-5-31 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(58, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(59, 'consuelo172@hotmail.com', 'consuelo172@hotmail.com', 'María Consuelo Preciado', 'María Consuelo Preciado', 1, 5, 'María Consuelo', 1, 'PENDIENTE', '2016-6-1 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(59, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(60, 'josgabrielr@gmail.com', 'josgabrielr@gmail.com', 'José Gabriel Ramírez', 'José Gabriel Ramírez', 0, 5, 'José Gabriel', 1, 'PENDIENTE', '2016-6-2 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(60, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(61, 'vanefuentessalas@gmail.com', 'vanefuentessalas@gmail.com', 'Vanessa Fuentes Salas', 'Vanessa Fuentes Salas', 1, 5, 'Vanessa', 1, 'PENDIENTE', '2016-6-3 18:46', '2016-6-22 9:29');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(61, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(62, 'juannuosuna@gmail.com', 'juannuosuna@gmail.com', 'Juan Guillermo Nuñez Osuna', 'Juan Guillermo Nuñez Osuna', 0, 5, 'Juan Guillermo', 1, 'PENDIENTE', '2016-6-4 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(62, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(63, 'jomsuarezal@hotmail.com', 'jomsuarezal@hotmail.com', 'Jorge Suárez', 'Jorge Suárez', 0, 5, 'Jorge', 1, 'PENDIENTE', '2016-6-5 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(63, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(64, 'almedica06@hotmail.com', 'almedica06@hotmail.com', 'Alberto Medina C.', 'Alberto Medina C.', 0, 5, 'Alberto', 1, 'PENDIENTE', '2016-6-6 18:46', '2016-5-6 9:11');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(64, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(65, 'rigorigo2750@hotmail.com', 'rigorigo2750@hotmail.com', 'Rigoberto Giraldo', 'Rigoberto Giraldo', 0, 5, 'Rigoberto', 1, 'PENDIENTE', '2016-6-7 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(65, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(66, 'ginamilena90@gmail.com', 'ginamilena90@gmail.com', 'Gina Milena Rodriguez Sarmiento', 'Gina Milena Rodriguez Sarmiento', 1, 5, 'Gina Milena', 1, 'PENDIENTE', '2016-6-8 18:46', '2016-5-6 11:3');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(66, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(67, 'germants81@gmail.com', 'germants81@gmail.com', 'Germán .', 'Germán .', 0, 5, 'Germán', 1, 'PENDIENTE', '2016-6-9 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(67, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(68, 'eleele62@yahoo.com', 'eleele62@yahoo.com', 'Liliana Laverde', 'Liliana Laverde', 1, 5, 'Liliana', 1, 'PENDIENTE', '2016-6-10 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(68, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(69, 'biktor@gmail.com', 'biktor@gmail.com', 'Victor Adrián Santafé Torres', 'Victor Adrián Santafé Torres', 1, 5, 'Victor Adrián', 1, 'PENDIENTE', '2016-6-11 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(69, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(70, 'philenaeva@gmail.com', 'philenaeva@gmail.com', 'Filena Jiménez', 'Filena Jiménez', 1, 5, 'Filena', 1, 'PENDIENTE', '2016-6-12 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(70, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(71, 'Camilo.casallas.q@outlook.com', 'Camilo.casallas.q@outlook.com', 'Camilo Casallas', 'Camilo Casallas', 0, 5, 'Camilo', 1, 'PENDIENTE', '2016-6-13 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(71, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(72, 'Mara.9109@hotmail.com', 'Mara.9109@hotmail.com', 'Maribel .', 'Maribel .', 1, 5, 'Maribel', 1, 'PENDIENTE', '2016-6-14 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(72, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(73, 'criwder@gmail.com', 'criwder@gmail.com', 'Maureen Vargas', 'Maureen Vargas', 1, 5, 'Maureen', 1, 'PENDIENTE', '2016-6-15 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(73, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(74, 'bryanhortua@hotmail.com', 'bryanhortua@hotmail.com', 'Bryan  Hortua', 'Bryan  Hortua', 0, 5, 'Bryan ', 1, 'PENDIENTE', '2016-6-16 18:46', '2016-5-27 2:1');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(74, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(75, 'macerari@gmail.com', 'macerari@gmail.com', 'Maria .', 'Maria .', 1, 5, 'Maria', 1, 'PENDIENTE', '2016-6-17 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(75, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(76, 'jaramilloaranguren@hotmail.com', 'jaramilloaranguren@hotmail.com', 'Jorge Jaramillo A', 'Jorge Jaramillo A', 0, 5, 'Jorge', 1, 'PENDIENTE', '2016-6-18 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(76, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(77, 'gtorresherrera@gmail.com', 'gtorresherrera@gmail.com', 'Gustavo Torres Herrera', 'Gustavo Torres Herrera', 0, 5, 'Gustavo', 1, 'PENDIENTE', '2016-6-19 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(77, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(78, 'lei_dy122@hotmail.com', 'lei_dy122@hotmail.com', 'Leidy Katherine .', 'Leidy Katherine .', 1, 5, 'Leidy Katherine', 1, 'PENDIENTE', '2016-6-20 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(78, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(79, 'andresfepo666@gmail.com', 'andresfepo666@gmail.com', 'Andres Felipe Duarte', 'Andres Felipe Duarte', 1, 5, 'Andres Felipe', 1, 'PENDIENTE', '2016-6-21 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(79, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(80, 'andresfelipeduarte16@hotmail.com', 'andresfelipeduarte16@hotmail.com', 'Andres Felipe Duarte', 'Andres Felipe Duarte', 0, 5, 'Andres Felipe', 1, 'PENDIENTE', '2016-6-22 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(80, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(81, 'egroj23@gmail.com', 'egroj23@gmail.com', 'Jorge Gómez', 'Jorge Gómez', 0, 5, 'Jorge', 1, 'PENDIENTE', '2016-6-23 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(81, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(82, 'vegueta.42@hotmail.com', 'vegueta.42@hotmail.com', 'Andres .', 'Andres .', 0, 5, 'Andres', 1, 'PENDIENTE', '2016-6-24 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(82, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(83, 'lvaleb98@gmail.com', 'lvaleb98@gmail.com', 'Valentina .', 'Valentina .', 1, 5, 'Valentina', 1, 'PENDIENTE', '2016-6-25 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(83, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(84, 'pauanduja1@hotmail.com', 'pauanduja1@hotmail.com', 'Paula Duran', 'Paula Duran', 1, 5, 'Paula', 1, 'PENDIENTE', '2016-6-26 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(84, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(85, 'sergio__h2000@hotmail.com', 'sergio__h2000@hotmail.com', 'Sergio .', 'Sergio .', 0, 5, 'Sergio', 1, 'PENDIENTE', '2016-6-27 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(85, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(86, 'paduranj@unal.edu.co', 'paduranj@unal.edu.co', 'Paula Duran', 'Paula Duran', 1, 5, 'Paula', 1, 'PENDIENTE', '2016-6-28 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(86, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(87, 'Oalejandra888@gmail.com', 'Oalejandra888@gmail.com', 'Alejandra Ospina', 'Alejandra Ospina', 1, 5, 'Alejandra', 1, 'PENDIENTE', '2016-6-29 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(87, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(88, 'diego.orjuela@gmail.com', 'diego.orjuela@gmail.com', 'Diego Orjuela', 'Diego Orjuela', 0, 5, 'Diego', 1, 'PENDIENTE', '2016-6-30 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(88, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(89, 'jcrinconl@unal.edu.co', 'jcrinconl@unal.edu.co', 'Juan Camilo Rincon Leyton', 'Juan Camilo Rincon Leyton', 1, 5, 'Juan Camilo', 1, 'PENDIENTE', '2016-7-1 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(89, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(90, 'alienthschrei@hotmail.com', 'alienthschrei@hotmail.com', 'Solangie Valenzuela', 'Solangie Valenzuela', 1, 5, 'Solangie', 1, 'PENDIENTE', '2016-7-2 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(90, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(91, 'nardamaria1@yahoo.co.uk', 'nardamaria1@yahoo.co.uk', 'Maria Leonarda Aristizábal', 'Maria Leonarda Aristizábal', 1, 5, 'Maria Leonarda', 1, 'PENDIENTE', '2016-7-3 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(91, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(92, 'samuelmath@gmail.com', 'samuelmath@gmail.com', 'Samuel Adolfo Navarro Serna', 'Samuel Adolfo Navarro Serna', 0, 5, 'Samuel Adolfo', 1, 'PENDIENTE', '2016-7-4 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(92, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(93, 'cecilialpz0@gmail.com', 'cecilialpz0@gmail.com', 'Marta López Buitrago', 'Marta López Buitrago', 1, 5, 'Marta', 1, 'PENDIENTE', '2016-7-5 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(93, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(94, 'fundacionecosuenos1@gmail.com', 'fundacionecosuenos1@gmail.com', 'Sonia Camacho', 'Sonia Camacho', 0, 5, 'Sonia', 1, 'PENDIENTE', '2016-7-6 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(94, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(95, 'mateovasquez1303@gmail.com', 'mateovasquez1303@gmail.com', 'Mateo Vasquez', 'Mateo Vasquez', 0, 5, 'Mateo', 1, 'PENDIENTE', '2016-7-7 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(95, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(96, 'nfbauti82@gmail.com', 'nfbauti82@gmail.com', 'Fernando Bautista', 'Fernando Bautista', 0, 5, 'Fernando', 1, 'PENDIENTE', '2016-7-8 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(96, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(97, 'salviega6@gmail.com', 'salviega6@gmail.com', 'Santiago Viana', 'Santiago Viana', 0, 5, 'Santiago', 1, 'PENDIENTE', '2016-7-9 18:46', '2016-8-5 12:26');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(97, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(98, 'herondale92@gmail.com', 'herondale92@gmail.com', 'Ana Maria Martinez', 'Ana Maria Martinez', 1, 5, 'Ana Maria', 1, 'PENDIENTE', '2016-7-10 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(98, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(99, 'gjod@hotmail.com', 'gjod@hotmail.com', 'William Diaz', 'William Diaz', 0, 5, 'William', 1, 'PENDIENTE', '2016-7-11 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(99, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(100, 'tifa243@hotmail.com', 'tifa243@hotmail.com', 'Stefany Hernández', 'Stefany Hernández', 1, 5, 'Stefany', 1, 'PENDIENTE', '2016-7-12 18:46', '2016-5-10 12:48');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(100, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(101, 'Jan.halos@gmail.com', 'Jan.halos@gmail.com', 'Jans Halos Chloz', 'Jans Halos Chloz', 0, 5, 'Jans', 1, 'PENDIENTE', '2016-7-13 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(101, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(102, 'mojica94@hotmail.com', 'mojica94@hotmail.com', 'Mauricio .', 'Mauricio .', 0, 5, 'Mauricio', 1, 'PENDIENTE', '2016-7-14 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(102, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(103, 'lauralrg10@hotmail.com', 'lauralrg10@hotmail.com', 'Lucía Gómez', 'Lucía Gómez', 1, 5, 'Lucía', 1, 'PENDIENTE', '2016-7-15 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(103, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(104, 'luislinper@gmail.com', 'luislinper@gmail.com', 'Luis Alberto Lindo', 'Luis Alberto Lindo', 0, 5, 'Luis Alberto', 1, 'PENDIENTE', '2016-7-16 18:46', '2016-5-13 13:8');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(104, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(105, 'sebastian.pedagogia@gmail.com', 'sebastian.pedagogia@gmail.com', 'Sebastian Calderón', 'Sebastian Calderón', 0, 5, 'Sebastian', 1, 'PENDIENTE', '2016-7-17 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(105, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(106, 'caronte100@gmail.com', 'caronte100@gmail.com', 'Anibal C.', 'Anibal C.', 0, 5, 'Anibal', 1, 'PENDIENTE', '2016-7-18 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(106, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(107, 'jomgonzalezal@gmail.com', 'jomgonzalezal@gmail.com', 'Jonathan Gonzalez', 'Jonathan Gonzalez', 0, 5, 'Jonathan', 1, 'PENDIENTE', '2016-7-19 18:46', '2016-5-10 22:4');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(107, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(108, 'miliky8@gmail.com', 'miliky8@gmail.com', 'Miliky Alvarez', 'Miliky Alvarez', 0, 5, 'Miliky', 1, 'PENDIENTE', '2016-7-20 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(108, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(109, 'niky.ramirez.98@hotmail.com', 'niky.ramirez.98@hotmail.com', 'Nicole Ramirez', 'Nicole Ramirez', 1, 5, 'Nicole', 1, 'PENDIENTE', '2016-7-21 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(109, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(110, 'cesaroyuela13@gmail.com', 'cesaroyuela13@gmail.com', 'Cesar Oyuela', 'Cesar Oyuela', 0, 5, 'Cesar', 1, 'PENDIENTE', '2016-7-22 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(110, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(111, 'lacamicc1@gmail.com', 'lacamicc1@gmail.com', 'Laura Camila .', 'Laura Camila .', 1, 5, 'Laura Camila', 1, 'PENDIENTE', '2016-7-23 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(111, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(112, 'lacamicc@hotmail.com', 'lacamicc@hotmail.com', 'Laura Camila .', 'Laura Camila .', 1, 5, 'Laura Camila', 1, 'PENDIENTE', '2016-7-24 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(112, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(113, 'alvaroguerreromadrid@gmail.com', 'alvaroguerreromadrid@gmail.com', 'Alvaro Guerrero', 'Alvaro Guerrero', 0, 5, 'Alvaro', 1, 'PENDIENTE', '2016-7-25 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(113, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(114, 'caareyesci@unal.edu.co', 'caareyesci@unal.edu.co', 'Carlos Andrés Reyes Cifuentes', 'Carlos Andrés Reyes Cifuentes', 1, 5, 'Carlos Andrés', 1, 'PENDIENTE', '2016-7-26 18:46', '2016-6-7 19:10');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(114, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(115, 'francyayr@gmail.com', 'francyayr@gmail.com', 'Francy Andrea Yucumá Ramírez', 'Francy Andrea Yucumá Ramírez', 1, 5, 'Francy Andrea', 1, 'PENDIENTE', '2016-7-27 18:46', '2016-6-1 21:49');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(115, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(116, 'ghgomezl@gmail.com', 'ghgomezl@gmail.com', 'Guillermo Hernán Gómez López', 'Guillermo Hernán Gómez López', 0, 5, 'Guillermo Hernán', 1, 'PENDIENTE', '2016-7-28 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(116, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(117, 'Ldys@hotmail.com', 'Ldys@hotmail.com', 'Santiago Marín Vargas', 'Santiago Marín Vargas', 0, 5, 'Santiago', 1, 'PENDIENTE', '2016-7-29 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(117, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(118, 'lizie.samudioher@gmail.com', 'lizie.samudioher@gmail.com', 'Lizeth Samudio', 'Lizeth Samudio', 1, 5, 'Lizeth', 1, 'PENDIENTE', '2016-7-30 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(118, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(119, 'cturizo@unal.edu.co', 'cturizo@unal.edu.co', 'Carol .', 'Carol .', 1, 5, 'Carol', 1, 'PENDIENTE', '2016-7-31 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(119, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(120, 'hejocalo_1312@hotmail.com', 'hejocalo_1312@hotmail.com', 'Hellen Calderón', 'Hellen Calderón', 1, 5, 'Hellen', 1, 'PENDIENTE', '2016-8-1 18:46', '2016-5-10 12:1');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(120, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(121, 'jhon.misfit@hotmail.com', 'jhon.misfit@hotmail.com', 'Jhon Bernal', 'Jhon Bernal', 0, 5, 'Jhon', 1, 'PENDIENTE', '2016-8-2 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(121, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(122, 'nicolas42125@gmail.com', 'nicolas42125@gmail.com', 'Joe .', 'Joe .', 0, 5, 'Joe', 1, 'PENDIENTE', '2016-8-3 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(122, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(123, 'monroyramirez@hotmail.com', 'monroyramirez@hotmail.com', 'Efrain .', 'Efrain .', 0, 5, 'Efrain', 1, 'PENDIENTE', '2016-8-4 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(123, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(124, 'yeandrap_01@hotmail.com', 'yeandrap_01@hotmail.com', 'Paola .', 'Paola .', 1, 5, 'Paola', 1, 'PENDIENTE', '2016-8-5 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(124, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(125, 'aleja_1408@live.com', 'aleja_1408@live.com', 'Alejandra Aldana', 'Alejandra Aldana', 1, 5, 'Alejandra', 1, 'PENDIENTE', '2016-8-6 18:46', '2016-5-10 13:45');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(125, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(126, 'condorvigilante@hotmail.com', 'condorvigilante@hotmail.com', 'Oscar Rodríguez Piragua', 'Oscar Rodríguez Piragua', 0, 5, 'Oscar', 1, 'PENDIENTE', '2016-8-7 18:46', '2016-5-12 14:6');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(126, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(127, 'normaelizabethpinzon@hotmail.com', 'normaelizabethpinzon@hotmail.com', 'Elizabeth Pinzón', 'Elizabeth Pinzón', 1, 5, 'Elizabeth', 1, 'PENDIENTE', '2016-8-8 18:46', '2016-5-10 21:58');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(127, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(128, 'frios.231@gmail.com', 'frios.231@gmail.com', 'Felipe Rios', 'Felipe Rios', 0, 5, 'Felipe', 1, 'PENDIENTE', '2016-8-9 18:46', '2016-5-10 11:13');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(128, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(129, 'lnrojas18@gmail.com', 'lnrojas18@gmail.com', 'Laura Rojas Acosta', 'Laura Rojas Acosta', 1, 5, 'Laura', 1, 'PENDIENTE', '2016-8-10 18:46', '2016-5-10 11:12');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(129, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(130, 'bnguzmanr@unal.edu.co', 'bnguzmanr@unal.edu.co', 'Nicolás Guzmán', 'Nicolás Guzmán', 0, 5, 'Nicolás', 1, 'PENDIENTE', '2016-8-11 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(130, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(131, 'andresfjb@hotmail.com', 'andresfjb@hotmail.com', 'Julian Garzón', 'Julian Garzón', 0, 5, 'Julian', 1, 'PENDIENTE', '2016-8-12 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(131, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(132, 'karen.navacandamil@gmail.com', 'karen.navacandamil@gmail.com', 'Karen  Navarrete', 'Karen  Navarrete', 1, 5, 'Karen ', 1, 'PENDIENTE', '2016-8-13 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(132, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(133, 'sergio14-man@hotmail.com', 'sergio14-man@hotmail.com', 'Sergio .', 'Sergio .', 0, 5, 'Sergio', 1, 'PENDIENTE', '2016-8-14 18:46', '2016-5-10 18:47');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(133, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(134, 'tita59@hotmail.com', 'tita59@hotmail.com', 'Patricia .', 'Patricia .', 1, 5, 'Patricia', 1, 'PENDIENTE', '2016-8-15 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(134, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(135, 'ojleivap@gmail.com', 'ojleivap@gmail.com', 'Oscar Leiva', 'Oscar Leiva', 0, 5, 'Oscar', 1, 'PENDIENTE', '2016-8-16 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(135, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(136, 'diegoandresalfonso@hotmail.com', 'diegoandresalfonso@hotmail.com', 'Diego Andrés Alfonso', 'Diego Andrés Alfonso', 0, 5, 'Diego Andrés', 1, 'PENDIENTE', '2016-8-17 18:46', '2016-6-7 15:35');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(136, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(137, 'idabark24@hotmail.com', 'idabark24@hotmail.com', 'Iván Barajas', 'Iván Barajas', 0, 5, 'Iván', 1, 'PENDIENTE', '2016-8-18 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(137, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(138, 'Ivanbarajashurtado@gmail.com', 'Ivanbarajashurtado@gmail.com', 'Iván Barajas Hurtado', 'Iván Barajas Hurtado', 0, 5, 'Iván', 1, 'PENDIENTE', '2016-8-19 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(138, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(139, 'luisafernandahavila@gmail.com', 'luisafernandahavila@gmail.com', 'Luisa Fernanda .', 'Luisa Fernanda .', 0, 5, 'Luisa Fernanda', 1, 'PENDIENTE', '2016-8-20 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(139, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(140, 'danielrcardenas@gmail.com', 'danielrcardenas@gmail.com', 'Daniel Cárdenas', 'Daniel Cárdenas', 0, 5, 'Daniel', 1, 'PENDIENTE', '2016-8-21 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(140, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(141, 'calbertosuarezs@gmail.com', 'calbertosuarezs@gmail.com', 'Carlos Alberto Suarez', 'Carlos Alberto Suarez', 0, 5, 'Carlos Alberto', 1, 'PENDIENTE', '2016-8-22 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(141, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(142, 'alfredo.alarcon@sigavl.com', 'alfredo.alarcon@sigavl.com', 'Alfredo Alarcón', 'Alfredo Alarcón', 0, 5, 'Alfredo', 1, 'PENDIENTE', '2016-8-23 18:46', '2016-6-21 20:1');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(142, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(143, 'juliansuarezbag@hotmail.com', 'juliansuarezbag@hotmail.com', 'Julian David Suarez', 'Julian David Suarez', 0, 5, 'Julian David', 1, 'PENDIENTE', '2016-8-24 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(143, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');
INSERT INTO `lb_usuarios`(`inUsuario`,`txUsuTelefono`,`txUsuEmail`,`txUsuNombre`,`txUsuImagen`,`inUsuGenero`,`inUsuLugar`,`txUsuNomMostrar`,`inUsuEstado`,`txUsuClave`,`feFecRegistro`,`feUsuUltIngreso`)VALUES(144, 'carlosnicolas6@gmail.com', 'carlosnicolas6@gmail.com', 'Carlos .', 'Carlos .', 0, 5, 'Carlos', 1, 'PENDIENTE', '2016-8-25 18:46', '');     INSERT INTO `dotex4read`.`lb_planesusuarios`(`inUsuPlan`,`inPlUsPlanes`,`fePlUsInicio`,`fePlUsFin`)VALUES(144, 1, '2016-01-01 00:00:00', '2046-01-01 00:00:00');

INSERT INTO lb_membresias (inmemusuario, inmemgrupo) 
select inusuario, 1 from lb_usuarios;



SELECT * FROM dotex4read.lb_usuarios;
commit;
commit;
commit;
