SELECT * FROM dotex4read.lb_editoriales;

delete FROM dotex4read.lb_editoriales where inIdEditorial > 0;
alter table dotEx4read.lb_editoriales auto_increment=1;
commit;
commit;commit;
commit;commit;
commit;commit;
commit;

INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('3R Editores');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('ABC');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Academia Charlot');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Addison Wesley Longman');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Aims Intl Books Corp');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Alba');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Alcaná Libros');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Alfaguara Ediciones S.A.');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Alfaomega');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Alianza Editorial');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Alta Fulla');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Altea');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Andrés Bello');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Angeles Camargo, Cátedra');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Arango');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Areté');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Ariel');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Azerbaiyan');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Bantam Classic');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Bedout');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Biblioteca de Bolsillo');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Biblioteca de iniciación Filosófica');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Biblioteca Edaf');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Biblioteca Juvenil Alianza');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Biblioteca Psicologías del siglo XX');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Booket');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Books4pocket');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Bronce');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Byblos');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Camm');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Círculo de lectores');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Colección Austral');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Colección Laguna');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Comcosur');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Compañía General De Ediciones');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Corregidor');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Destino');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Deusto');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Diana');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Distribuidora Aguilar');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('EAFIT');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('EDAF S.A.');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Edebé');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Edhasa');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Ediciones Alborada');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Ediciones B');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Ediciones Casa Silva');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Ediciones Cristiandad');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Ediciones de Bolsillo');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Ediciones Macchi');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Ediciones Martinez Roca');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Ediciones Nueva Visión');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Ediciones Obelisco');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Ediciones ORBIS');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Ediciones Península');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Ediciones Prolec');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Ediciones SM');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Ediciones UNAULA');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Ediciones Uninorte');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Ediciones Urano S.A');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Edilux Ediciones');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Edimat Libros');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Editores Mexicanos');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Editorial Anagrama');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Editorial Andes');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Editorial Bruguera');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Editorial Catedra');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Editorial Crítica');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Editorial Documentos Periodisticos');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Editorial Everest S.A.');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Editorial Grad');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Editorial Herder');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Editorial Juventud');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Editorial Kapelusz');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Editorial Kimpres Ltda.');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Editorial Labor');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Editorial Oveja Negra');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Editorial Planeta ');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Editorial Printer');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Editorial Seix Barral');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Editorial Vicens Vives');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Educar S.A.');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('El Áncora Editores');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('El anden');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('El Arca de Papel');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('El Ateneo');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('El Tiempo');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('EM');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Ernst Klett Verlag');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Escuela Española D.L.');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Espasa');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Everest Pub');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Fabula Tusquets Editores');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Fondo de Cultura Económica');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Fondo de Cultura Económica USA');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Fontanella');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Gediza Editorial');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Gente Nueva');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Grandes Autores, Grandes Obras');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Grijalbo');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Grupera');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Grupo Anaya S.A.');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Grupo Carvajal');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Grupo Editorial Norma');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Grupo Editorial Tomo');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Grupo Latino LTDA.');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Grupo Océano');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Grupo Patria Cultural');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Grupo Zeta');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Harla S.A');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Herder');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Hermes');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Icono Editorial');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Imprenta Nacional de Colombia');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Instituto Distrital de las Artes');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Integral');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Intermedio Editores Ltda.');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('International Thomson');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Istmo');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Javier Vergara Editor');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Kapelusz');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('KEL');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('La Nación');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Laboratorios Incobra');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Language World');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Larousse');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Laurel-Leaf Book');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Lauro');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Letras Universales');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Librería Suramérica');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Libresa');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Libro amigo');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Libros & Libros S.A.');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Libsa');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Literatura Mondadori');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Literatura Random House');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('LUMEN');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Macmillan');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Mc Graw Hill');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Mexico');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Millenium');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Mondadori');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Monte Avila');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('MR Ediciones');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Negret books');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Net Educativa');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Noguer');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Noguer Y Caralt Editore');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Nueva Imagen');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Obelisco');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Obras');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Obras Maestras del Siglo XX');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Océano De México');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Olimpica');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Oniro');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Orbis');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('P & J. Cambio 16');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Paidos Iberica Ediciones SA');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Panamericana Editorial');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Parke-Davis');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Parramón Ediciones');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Pearson');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Penguin Random House Grupo Editorial');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Planeta Lector');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Planeta S.A.');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Planeta, Agostini');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Planeta, Seix Barral');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Plata');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Plaza & Janés Editores');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Plutón Ediciones');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Prentice Hall');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Publicaciones Semana S.A');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Publicaciones y Ediciones Salamandra S.A.');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Punto de Lectura');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Random House Mondadori');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Rayo');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Red Editorial Iberoamericana');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Rei');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Reverté S.A');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Ricardo Aguilera');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Salamandra');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Salvat');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Santillana');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Sarpe');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Scholastic');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Sefirá');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Siglo Veintiuno Ediciones ');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Sin especificar');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Sirio');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Siruela');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Sol90');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Sudamericana');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Suma');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Susaeta Ediciones');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Taller del éxito');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Taurus');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Tendencias');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Tercer Mundo Editores');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Terramar');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Thassalia');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Thomson Learning');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Tilde');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Touchstone');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Tusquets Editor');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Unilever');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Universidad de Antioquia');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Urano');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Vergara');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Vicens Vives');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Villegas Editores S.A.');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Vintage Books');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('W. W. Norton & Company');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('YearLing');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Zeta');
INSERT INTO `lb_editoriales`(`txEdiNombre`)VALUES('Zig-Zag');
