LbLugares:
    type: entity
    table: lb_lugares
    indexes:
        fk_lb_lugares_lb_lugares1_idx:
            columns:
                - inLugPadre
    id:
        inlugar:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: inLugar
            generator:
                strategy: IDENTITY
    fields:
        txlugcodigo:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: txLugCodigo
        txlugnombre:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: txLugNombre
    manyToOne:
        inlugpadre:
            targetEntity: LbLugares
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                inLugPadre:
                    referencedColumnName: inLugar
            orphanRemoval: false
    lifecycleCallbacks: {  }
