LbOfertas:
    type: entity
    table: lb_ofertas
    indexes:
        fk_lb_ofertas_lb_membresias1_idx:
            columns:
                - inOfeMembresia
    id:
        inoferta:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: inOferta
            generator:
                strategy: IDENTITY
    fields:
        feofefecha:
            type: datetime
            nullable: false
            comment: ''
            column: feOfeFecha
        inofevigencia:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Días de vigencia de la oferta'
            default: '1'
            column: inOfeVigencia
        inofeactiva:
            type: integer
            nullable: true
            unsigned: false
            comment: '0:Inactiva - 1:Activa'
            default: '1'
            column: inOfeActiva
        inofeabierta:
            type: integer
            nullable: true
            unsigned: false
            comment: "Cerrada significa que solo se publicará y se tendrá acceso para los usuarios de los grupos a los que pertenezco. Abierta significa que es a nivel general. Por ahora se va a tener cerrada ya que todo el mundo pertenece a un solo grupo.\n0: Cerrada - 1:Abierta"
            default: '0'
            column: inOfeAbierta
    manyToOne:
        inofemembresia:
            targetEntity: LbMembresias
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                inOfeMembresia:
                    referencedColumnName: inMembresia
            orphanRemoval: false
    lifecycleCallbacks: {  }
