LbSesiones:
    type: entity
    table: lb_sesiones
    indexes:
        fk_lb_sesiones_lb_dispusuarios1_idx:
            columns:
                - inSesDispUsuario
    id:
        insesion:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: inSesion
            generator:
                strategy: IDENTITY
    fields:
        txsesnumero:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: txSesNumero
        insesactiva:
            type: integer
            nullable: false
            unsigned: false
            comment: '0: Inactiva 1: Activa'
            default: '1'
            column: inSesActiva
        fesesfechaini:
            type: datetime
            nullable: false
            comment: ''
            column: feSesFechaIni
        fesesfechafin:
            type: datetime
            nullable: true
            comment: ''
            column: feSesFechaFin
    manyToOne:
        insesdispusuario:
            targetEntity: LbDispusuarios
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                inSesDispUsuario:
                    referencedColumnName: inDispUsuario
            orphanRemoval: false
    lifecycleCallbacks: {  }
