<?php

namespace Proxies\__CG__\Libreame\BackendBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LbUsuarios extends \Libreame\BackendBundle\Entity\LbUsuarios implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'inusuario', 'txusuemail', 'txusutelefono', 'txusunombre', 'inusugenero', 'txusuimagen', 'txusunommostrar', 'feusunacimiento', 'txusuvalidacion', 'inusuestado', 'txusuclave', 'inusulugar');
        }

        return array('__isInitialized__', 'inusuario', 'txusuemail', 'txusutelefono', 'txusunombre', 'inusugenero', 'txusuimagen', 'txusunommostrar', 'feusunacimiento', 'txusuvalidacion', 'inusuestado', 'txusuclave', 'inusulugar');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (LbUsuarios $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getInusuario()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getInusuario();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInusuario', array());

        return parent::getInusuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxusuemail($txusuemail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxusuemail', array($txusuemail));

        return parent::setTxusuemail($txusuemail);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxusuemail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxusuemail', array());

        return parent::getTxusuemail();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxusutelefono($txusutelefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxusutelefono', array($txusutelefono));

        return parent::setTxusutelefono($txusutelefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxusutelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxusutelefono', array());

        return parent::getTxusutelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxusunombre($txusunombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxusunombre', array($txusunombre));

        return parent::setTxusunombre($txusunombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxusunombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxusunombre', array());

        return parent::getTxusunombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setInusugenero($inusugenero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInusugenero', array($inusugenero));

        return parent::setInusugenero($inusugenero);
    }

    /**
     * {@inheritDoc}
     */
    public function getInusugenero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInusugenero', array());

        return parent::getInusugenero();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxusuimagen($txusuimagen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxusuimagen', array($txusuimagen));

        return parent::setTxusuimagen($txusuimagen);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxusuimagen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxusuimagen', array());

        return parent::getTxusuimagen();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxusunommostrar($txusunommostrar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxusunommostrar', array($txusunommostrar));

        return parent::setTxusunommostrar($txusunommostrar);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxusunommostrar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxusunommostrar', array());

        return parent::getTxusunommostrar();
    }

    /**
     * {@inheritDoc}
     */
    public function setFeusunacimiento($feusunacimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeusunacimiento', array($feusunacimiento));

        return parent::setFeusunacimiento($feusunacimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getFeusunacimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeusunacimiento', array());

        return parent::getFeusunacimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxusuvalidacion($txusuvalidacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxusuvalidacion', array($txusuvalidacion));

        return parent::setTxusuvalidacion($txusuvalidacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxusuvalidacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxusuvalidacion', array());

        return parent::getTxusuvalidacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setInusuestado($inusuestado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInusuestado', array($inusuestado));

        return parent::setInusuestado($inusuestado);
    }

    /**
     * {@inheritDoc}
     */
    public function getInusuestado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInusuestado', array());

        return parent::getInusuestado();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxusuclave($txusuclave)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxusuclave', array($txusuclave));

        return parent::setTxusuclave($txusuclave);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxusuclave()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxusuclave', array());

        return parent::getTxusuclave();
    }

    /**
     * {@inheritDoc}
     */
    public function setInusulugar(\Libreame\BackendBundle\Entity\LbLugares $inusulugar = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInusulugar', array($inusulugar));

        return parent::setInusulugar($inusulugar);
    }

    /**
     * {@inheritDoc}
     */
    public function getInusulugar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInusulugar', array());

        return parent::getInusulugar();
    }

    /**
     * {@inheritDoc}
     */
    public function creaUsuario($pSolicitud, $Lugar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'creaUsuario', array($pSolicitud, $Lugar));

        return parent::creaUsuario($pSolicitud, $Lugar);
    }

    /**
     * {@inheritDoc}
     */
    public function cantMsgUsr($usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'cantMsgUsr', array($usuario));

        return parent::cantMsgUsr($usuario);
    }

}
