parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: 
    database_name: dotex4read
    database_user: root
    database_password: 'root'
    locale: en
    secret: 818540f6bc2c9676a5a44bdb6e65758b9dc2c2f4
    mailer_transport: smtp
    mailer_host: p3plcpnl0478.prod.phx3.secureserver.net
    mailer_user: registro@ex4read.co
    mailer_password: R3g15tr0
    #mailer_transport: gmail
    #mailer_host: null
    #mailer_user: baisicasas
    #mailer_password: b,4151c454s-
    #database_path: null
    
