parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: 
    database_name: dotex4read
    database_user: root
    database_password: 'root'
    locale: en
    secret: 818540f6bc2c9676a5a44bdb6e65758b9dc2c2f4
    mailer_transport: gmail
    mailer_host: null
    mailer_user: baisicasas
    mailer_password: b41s1c4s4s
    database_path: null
    
