Libreame\BackendBundle\Entity\LbCalificausuarios:
    type: entity
    table: lb_calificausuarios
    indexes:
        fk_lb_calificausuarios_lb_usuarios1_idx:
            columns:
                - inCalUsuCalifica
        fk_lb_calificausuarios_lb_usuarios2_idx:
            columns:
                - inCalUsuCalificado
    id:
        incalificacion:
            type: integer
            nullable: false
            unsigned: false
            comment: Id
            id: true
            column: inCalificacion
            generator:
                strategy: IDENTITY
    fields:
        incalcalificacion:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Calificación otorgada de 1 a 5'
            column: inCalCalificacion
        txcalobservacion:
            type: string
            nullable: true
            length: 500
            fixed: false
            comment: 'Comentario anexo a la calificacion'
            column: txCalObservacion
        incalreporteabuso:
            type: integer
            nullable: false
            unsigned: false
            comment: "0: No es reporte de abuso\n1: Si es reporte de abuso"
            default: '0'
            column: inCalReporteAbuso
    manyToOne:
        incalusucalifica:
            targetEntity: LbUsuarios
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                inCalUsuCalifica:
                    referencedColumnName: inUsuario
            orphanRemoval: false
        incalusucalificado:
            targetEntity: LbUsuarios
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                inCalUsuCalificado:
                    referencedColumnName: inUsuario
            orphanRemoval: false
    lifecycleCallbacks: {  }
