Libreame\BackendBundle\Entity\LbCalificausuarios:
    type: entity
    table: lb_calificausuarios
    indexes:
        fk_table1_lb_usuarios2_idx:
            columns:
                - inCalUsuCalificado
        fk_lb_calificausuarios_lb_usuarios3_idx:
            columns:
                - inCalUsuCalifica
        fk_lb_calificausuarios_lb_histEjemplar1_idx:
            columns:
                - inCalHisEjemplar
    id:
        inidcalifica:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Id del registro de calificacion'
            id: true
            column: inIDCalifica
            generator:
                strategy: IDENTITY
    fields:
        incalcalificacion:
            type: integer
            nullable: false
            unsigned: false
            comment: 'CAlificacion otorgada de 1 a 5'
            default: '1'
            column: inCalCalificacion
        txcalcomentario:
            type: string
            nullable: false
            length: 500
            fixed: false
            comment: 'Comentario realizado justificando la calificacion'
            default: Ninguno
            column: txCalComentario
        fecalfecha:
            type: datetime
            nullable: false
            comment: 'Fecha en que califica'
            column: feCalFecha
    manyToOne:
        incalhisejemplar:
            targetEntity: LbHistejemplar
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                inCalHisEjemplar:
                    referencedColumnName: inHistEjemplar
            orphanRemoval: false
        incalusucalifica:
            targetEntity: LbUsuarios
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                inCalUsuCalifica:
                    referencedColumnName: inUsuario
            orphanRemoval: false
        incalusucalificado:
            targetEntity: LbUsuarios
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                inCalUsuCalificado:
                    referencedColumnName: inUsuario
            orphanRemoval: false
    lifecycleCallbacks: {  }
