Libreame\BackendBundle\Entity\LbDetallestratos:
    type: entity
    table: lb_detallestratos
    indexes:
        fk_lb_detallestratos_lb_tratos1_idx:
            columns:
                - inDetTrato
        fk_lb_detallestratos_lb_ejemplares1_idx:
            columns:
                - inDetEjemplarUsr
        fk_lb_detallestratos_lb_usuarios1_idx:
            columns:
                - inDetUsuario
        fk_lb_detallestratos_lb_ejemplares2_idx:
            columns:
                - inDetEjemplarOtro
        fk_lb_detallestratos_lb_usuarios2_idx:
            columns:
                - inDetUsuarioOtro
    id:
        indetalletrato:
            type: integer
            nullable: false
            unsigned: false
            comment: Id
            id: true
            column: inDetalleTrato
            generator:
                strategy: IDENTITY
    fields:
        indetvalorusr:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: 'El valor que yo estoy dispuesto a pagar'
            default: '0'
            column: inDetValorUsr
        indetvalorotro:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: 'El valor que el otro me ofrecio'
            default: '0'
            column: inDetValorOtro
    manyToOne:
        indettrato:
            targetEntity: LbTratos
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                inDetTrato:
                    referencedColumnName: inTrato
            orphanRemoval: false
        indetejemplarusr:
            targetEntity: LbEjemplares
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                inDetEjemplarUsr:
                    referencedColumnName: inEjemplar
            orphanRemoval: false
        indetusuario:
            targetEntity: LbUsuarios
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                inDetUsuario:
                    referencedColumnName: inUsuario
            orphanRemoval: false
        indetejemplarotro:
            targetEntity: LbEjemplares
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                inDetEjemplarOtro:
                    referencedColumnName: inEjemplar
            orphanRemoval: false
        indetusuariootro:
            targetEntity: LbUsuarios
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                inDetUsuarioOtro:
                    referencedColumnName: inUsuario
            orphanRemoval: false
    lifecycleCallbacks: {  }
