Libreame\BackendBundle\Entity\LbDispusuarios:
    type: entity
    table: lb_dispusuarios
    indexes:
        fk_lb_dispusuarios_lb_usuarios1_idx:
            columns:
                - inDisUsuario
    id:
        indispusuario:
            type: integer
            nullable: false
            unsigned: false
            comment: ID
            id: true
            column: inDispUsuario
            generator:
                strategy: IDENTITY
    fields:
        txdisid:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: 'Identificacion del dispositivo'
            column: txDisID
        txdisnombre:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: 'Nombre del dispositivo'
            column: txDisNombre
        txdismarca:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: 'Marca del dispositivo'
            column: txDisMarca
        txdismodelo:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: 'Modelo del dispositivo'
            column: txDisModelo
        txdisso:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: 'Sistema operativo del dispositivo'
            column: txDisSO
    manyToOne:
        indisusuario:
            targetEntity: LbUsuarios
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                inDisUsuario:
                    referencedColumnName: inUsuario
            orphanRemoval: false
    lifecycleCallbacks: {  }
