Libreame\BackendBundle\Entity\LbEjemplares:
    type: entity
    table: lb_ejemplares
    indexes:
        fk_lb_ejemplares_lb_usuarios1_idx:
            columns:
                - inEjeUsuDueno
        fk_lb_ejemplares_lb_libros1_idx:
            columns:
                - inEjeLibro
    id:
        inejemplar:
            type: integer
            nullable: false
            unsigned: false
            comment: Id
            id: true
            column: inEjemplar
            generator:
                strategy: IDENTITY
    fields:
        inejecantidad:
            type: integer
            nullable: false
            unsigned: false
            comment: 'En algun momento se va a activar la posibilidad de que un usuario pueda publicar varios ejemplares de un mismo libro'
            default: '1'
            column: inEjeCantidad
        dbejeavaluo:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: 'Valor en el que el usuario avalua su libro'
            default: '0'
            column: dbEjeAvaluo
        txejeimagen:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: 'Guarda la url de la imagen'
            column: txEjeImagen
        inejepuntos:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Puntos que cuesta el ejemplar'
            default: '0'
            column: inEjePuntos
        inejepublicado:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Indica si el ejemplar esta publicado : Publicado :1 / No publicado : 0'
            default: '1'
            column: inEjePublicado
        inejebloqueado:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Un ejemplar se bloquea cuando un usuario ya ha gastado sus puntos pero no ha entregado ningun ejemplar, entonces el sistema bloquea tantos ejemplares requiera para asegurar que el usuario no los baje de dotEx4read: No bloqueado : 0 , Bloqueado : 1'
            default: '0'
            column: inEjeBloqueado
        inejeestado:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Estado de 1 a 10: 10 Excelente 1 : Muy deteriorado'
            default: '1'
            column: inEjeEstado
        inejecondicion:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Condicion del ejemplar: 0: Nuevo / 1: Usado'
            default: '1'
            column: inEjeCondicion
        inejesoloventa:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Indica si el ejemplar solo esta disponible para venta - 1: solo venta, 2: Venta y cambio'
            default: '0'
            column: inEjeSoloventa
        inejeestadonegocio:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Estado de la negocuación actual : 0 - No en negociacion,1 - Solicitado por usuario, 2 - En proceso de aprobación del negocio, 3 - Aprobado negocio por Ambos actores, 4 - En proceso de entrega\n5 - Entregado, 6 - Recibido'
            default: '0'
            column: inEjeEstadoNegocio
        inejereghisbloqueo:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Si está bloqueado, aquí se registra el ID de HisEjemplar de bloqueo vigente'
            default: '0'
            column: inEjeRegHisBloqueo
        inejereghispublicacion:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Si esta / No publicado Publicado, aquí se registra el ID de HisEjemplar de publicacion / Despublicacion vigente'
            default: '0'
            column: inEjeRegHisPublicacion
        inejereghisbajasis:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Si se dió de baja, aquí se registra el ID de HisEjemplar de Baja del sistema'
            default: '0'
            column: inEjeRegHisBajaSis
        inejereghisaprobdueno:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Si el dueno aprobó un negocio, aquí se registra el ID de HisEjemplar de Aprobacion'
            default: '0'
            column: inEjeRegHisAprobDueno
        inejereghisaprobsolic:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Si el solicitante aprobó un negocio, aquí se registra el ID de HisEjemplar de Aprobacion'
            default: '0'
            column: inEjeRegHisAprobSolic
        inejereghisentrega:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Si el dueno Entrego un ejemplar, aquí se registra el ID de HisEjemplar de Entrega'
            default: '0'
            column: inEjeRegHisEntrega
        inejereghisrecibido:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Si el solicitante Recibio un ejemplar, aquí se registra el ID de HisEjemplar de Recibo'
            default: '0'
            column: inEjeRegHisRecibido
            
    manyToOne:
        inejelibro:
            targetEntity: LbLibros
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                inEjeLibro:
                    referencedColumnName: inLibro
            orphanRemoval: false
        inejeusudueno:
            targetEntity: LbUsuarios
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                inEjeUsuDueno:
                    referencedColumnName: inUsuario
            orphanRemoval: false
    lifecycleCallbacks: {  }
