Libreame\BackendBundle\Entity\LbGenerosofrecidos:
    type: entity
    table: lb_generosofrecidos
    indexes:
        fk_lb_generosofrecidos_lb_generos1_idx:
            columns:
                - inGOfGenero
        fk_lb_generosofrecidos_lb_ofrecidos1_idx:
            columns:
                - inGOfOfrecido
    id:
        ingeneroofrecido:
            type: integer
            nullable: false
            unsigned: false
            comment: Id
            id: true
            column: inGeneroOfrecido
            generator:
                strategy: IDENTITY
    manyToOne:
        ingofgenero:
            targetEntity: LbGeneros
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                inGOfGenero:
                    referencedColumnName: inGenero
            orphanRemoval: false
        ingofofrecido:
            targetEntity: LbOfrecidos
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                inGOfOfrecido:
                    referencedColumnName: inOfrecido
            orphanRemoval: false
    lifecycleCallbacks: {  }
