Libreame\BackendBundle\Entity\LbHistoriaejemplar:
    type: entity
    table: lb_historiaejemplar
    indexes:
        fk_lb_historiaejemplar_lb_ejemplares1_idx:
            columns:
                - inHEjEjemplar
        fk_lb_historiaejemplar_lb_usuarios1_idx:
            columns:
                - inHEjUsuario
    id:
        inhistejemplar:
            type: integer
            nullable: false
            unsigned: false
            comment: Id
            id: true
            column: inHistEjemplar
            generator:
                strategy: IDENTITY
    fields:
        inhejfechahora:
            type: datetime
            nullable: false
            comment: 'Desde cuando el usuario tiene este ejemplar...para lo que lo registran en el sistema aparece la fecha de ese momento'
            column: inHEjFechaHora
        inhejmodo:
            type: integer
            nullable: false
            unsigned: false
            comment: "Indica:\n0: si es el usuario original (en ex4Read)\n1: si lo cambi贸 (recibiendolo)\n2: si lo compr贸 (recibiendolo)\n3. si lo cambio (entregandolo)\n4. si lo vendi贸 (entregandolo)\n5. si lo don贸 (entregandolo)"
            default: '0'
            column: inHEjModo
    manyToOne:
        inhejejemplar:
            targetEntity: LbEjemplares
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                inHEjEjemplar:
                    referencedColumnName: inEjemplar
            orphanRemoval: false
        inhejusuario:
            targetEntity: LbUsuarios
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                inHEjUsuario:
                    referencedColumnName: inUsuario
            orphanRemoval: false
    lifecycleCallbacks: {  }
