Libreame\BackendBundle\Entity\LbIndicepalabra:
    type: entity
    table: lb_indicepalabra
    indexes:
        fk_lb_indicepalabra_lb_libros1_idx:
            columns:
                - lbIndPalLibro
        idx_palabra:
            columns:
                - lbIndPalPalabra
        idx_palabraidioma:
            columns:
                - lbIndPalPalabra
                - lbIndPalIdioma
        idx_idiomapalabra:
            columns:
                - lbIndPalIdioma
                - lbIndPalPalabra
    id:
        lbindpalid:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Id  del indice'
            id: true
            column: lbIndPalId
            generator:
                strategy: IDENTITY
    fields:
        lbindpalpalabra:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: 'Palabra en minúscula'
            column: lbIndPalPalabra
        lbindpalidioma:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: 'Idioma del libro, que se hereda a la palabra, para filtrar'
            column: lbIndPalIdioma
    manyToOne:
        lbindpallibro:
            targetEntity: LbLibros
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                lbIndPalLibro:
                    referencedColumnName: inLibro
            orphanRemoval: false
    lifecycleCallbacks: {  }
