Libreame\BackendBundle\Entity\LbLibros:
    type: entity
    table: lb_libros
    indexes:
        idx_tipopublica:
            columns:
                - txLibTipoPublica
        idx_titulo:
            columns:
                - txLibTitulo
        idx_ISBN10:
            columns:
                - txLibCodigoOfic
        idx_ISBN13:
            columns:
                - txLibCodigoOfic13
        fk_lb_libros_lb_titulos1_idx:
            columns:
                - inLibTitTitulo
        fk_lb_libros_lb_idiomas1_idx:
            columns:
                - inLibIdioma
        indextxLibTitulo:
            columns:
                - txLibTitulo
                - txLibEdicionPais
                - txEdicionDescripcion
                - txLibCodigoOfic
                - txLibCodigoOfic13
                - txLibResumen
                - txLibVolumen
    id:
        inlibro:
            type: integer
            nullable: false
            unsigned: false
            comment: Id
            id: true
            column: inLibro
            generator:
                strategy: IDENTITY
    fields:
        txlibtipopublica:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Tipo publicacion 0:Libro 1:Revista.....'
            default: '0'
            column: txLibTipoPublica
        txlibtitulo:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: 'Titulo del libro'
            column: txLibTitulo
        txlibedicionanio:
            type: string
            nullable: true
            length: 10
            fixed: false
            comment: 'Anho de la edicion'
            column: txLibEdicionAnio
        txlibedicionnum:
            type: string
            nullable: true
            length: 10
            fixed: false
            comment: 'Numero de la edicion'
            column: txLibEdicionNum
        txlibedicionpais:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: 'Pais donde fue editado'
            column: txLibEdicionPais
        txediciondescripcion:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: 'Descripcion de la edicion: Pasta dura...de lujo, etc'
            column: txEdicionDescripcion
        txlibcodigoofic:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: 'ISBN - ISSN 10'
            column: txLibCodigoOfic
        txlibcodigoofic13:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: 'ISBN - ISSN 13'
            column: txLibCodigoOfic13
        txlibresumen:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'Resumen del libro'
            column: txLibResumen
        txlibtomo:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: 'Tomo o numero del libro'
            column: txLibTomo
        txlibvolumen:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: 'Volumen del libro'
            column: txLibVolumen
        txlibpaginas:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: 'Numero de paginas del libro'
            column: txLibPaginas
    manyToOne:
        inlibidioma:
            targetEntity: LbIdiomas
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                inLibIdioma:
                    referencedColumnName: inIdIdioma
            orphanRemoval: false
        inlibtittitulo:
            targetEntity: LbTitulos
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                inLibTitTitulo:
                    referencedColumnName: inIdTitulo
            orphanRemoval: false
    lifecycleCallbacks: {  }
