Libreame\BackendBundle\Entity\LbLugares:
    type: entity
    table: lb_lugares
    indexes:
        fk_lb_lugares_lb_lugares1_idx:
            columns:
                - inLugPadre
    id:
        inlugar:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Id Automático'
            id: true
            column: inLugar
            generator:
                strategy: IDENTITY
    fields:
        txlugcodigo:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: 'Código del lugar: Ejemplo en Colombia DIVIPOLA'
            column: txLugCodigo
        txlugnombre:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: 'Nombre del lugar, Ciudad, Depto, etc.'
            column: txLugNombre
        inlugelegible:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Indica si el registro puede ser elegido por un usuario 0: No elegible - 1 : Elegible'
            default: '0'
            column: inLugElegible
    manyToOne:
        inlugpadre:
            targetEntity: LbLugares
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                inLugPadre:
                    referencedColumnName: inLugar
            orphanRemoval: false
    lifecycleCallbacks: {  }
