Libreame\BackendBundle\Entity\LbOfertasfavoritas:
    type: entity
    table: lb_ofertasfavoritas
    indexes:
        fk_lb_ofertasfavoritas_lb_usuarios1_idx:
            columns:
                - inFavUsuario
        fk_lb_ofertasfavoritas_lb_ofertas1_idx:
            columns:
                - inFavOferta
    id:
        inofertafavorita:
            type: integer
            nullable: false
            unsigned: false
            comment: Id
            id: true
            column: inOfertaFavorita
            generator:
                strategy: IDENTITY
    fields:
        fefavfecha:
            type: datetime
            nullable: false
            comment: 'Fecha en la que la marque como favorita'
            column: feFavFecha
    manyToOne:
        infavusuario:
            targetEntity: LbUsuarios
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                inFavUsuario:
                    referencedColumnName: inUsuario
            orphanRemoval: false
        infavoferta:
            targetEntity: LbOfertas
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                inFavOferta:
                    referencedColumnName: inOferta
            orphanRemoval: false
    lifecycleCallbacks: {  }
