Libreame\BackendBundle\Entity\LbSolicitados:
    type: entity
    table: lb_solicitados
    indexes:
        fk_lb_solicitados_lb_ejemplares1_idx:
            columns:
                - inSolEjemplar
        fk_lb_solicitados_lb_ofertas1_idx:
            columns:
                - inSolOferta
        fk_lb_solicitados_lb_libros1_idx:
            columns:
                - inSolLibro
    id:
        idsolicitado:
            type: integer
            nullable: false
            unsigned: false
            comment: Id
            id: true
            column: IdSolicitado
            generator:
                strategy: IDENTITY
    fields:
        insoltransac:
            type: integer
            nullable: false
            unsigned: false
            comment: "La transacción que se desea con el ejemplar\n0:Compra 1:Cambio 2: Cualquiera 3: Alquiler(?)"
            default: '1'
            column: inSolTransac
        txsolobservacion:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: 'Observaciones especificas de la solicitud: No importa el estado, que no este rallado, el de pasta dura...etc.'
            column: txSolObservacion
        dbsolvaloferta:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: 'Valor que estoy dispuesto a pagar'
            default: '0'
            column: dbSolValOferta
        dbsolvaladic:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: 'Valor que estoy dispuesto a pagar adicional al libro que ofrezco'
            default: '0'
            column: dbSolValAdic
    manyToOne:
        insolejemplar:
            targetEntity: LbEjemplares
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                inSolEjemplar:
                    referencedColumnName: inEjemplar
            orphanRemoval: false
        insollibro:
            targetEntity: LbLibros
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                inSolLibro:
                    referencedColumnName: inLibro
            orphanRemoval: false
        insoloferta:
            targetEntity: LbOfertas
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                inSolOferta:
                    referencedColumnName: inOferta
            orphanRemoval: false
    lifecycleCallbacks: {  }
