Libreame\BackendBundle\Entity\LbUsuarios:
    type: entity
    table: lb_usuarios
    indexes:
        fk_lb_usuarios_lb_lugares1_idx:
            columns:
                - inUsuLugar
    uniqueConstraints:
        txUsuEmail_UNIQUE:
            columns:
                - txUsuEmail
        txUsuTelefono_UNIQUE:
            columns:
                - txUsuTelefono
    id:
        inusuario:
            type: integer
            nullable: false
            unsigned: false
            comment: Id
            id: true
            column: inUsuario
            generator:
                strategy: IDENTITY
    fields:
        txusuemail:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: 'Mail del usuario'
            column: txUsuEmail
        txusutelefono:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: 'Numero de telefono'
            default: '0'
            column: txUsuTelefono
        txusunombre:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: 'Nombre de usuario, por defecto es el email en el registro'
            column: txUsuNombre
        inusugenero:
            type: integer
            nullable: false
            unsigned: false
            comment: '''0: Masculino 1: Femenino 2: Sin especificar'''
            default: '2'
            column: inUsuGenero
        txusuimagen:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: 'Cuando no se especifica el sistema pone una por defecto.'
            column: txUsuImagen
        txusunommostrar:
            type: string
            nullable: true
            length: 20
            fixed: false
            comment: "Si no se digita nada, se muestra el txUsuNombre\n"
            column: txUsuNomMostrar
        feusunacimiento:
            type: datetime
            nullable: true
            comment: 'Fecha de nacimiento'
            column: feUsuNacimiento
        txusuvalidacion:
            type: string
            nullable: true
            length: 200
            fixed: false
            comment: 'Cuando se registra el usuario el sistema genera un código que se envía en el email de confirmación.  Este campo se utiliza tambien en los cambios de clave.'
            column: txUsuValidacion
        inusuestado:
            type: integer
            nullable: false
            unsigned: false
            comment: '0: Esperando confirmación 1: Activo 2: Cuarentena 3: Inactivo'
            default: '0'
            column: inUsuEstado
    manyToOne:
        inusulugar:
            targetEntity: LbLugares
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                inUsuLugar:
                    referencedColumnName: inLugar
            orphanRemoval: false
    lifecycleCallbacks: {  }
