<?php

namespace Proxies\__CG__\Libreame\BackendBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LbPlanes extends \Libreame\BackendBundle\Entity\LbPlanes implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'inplan', 'txplannombr', 'txplandescripcion', 'inplanvigente', 'inplanfree', 'inplandiasfree', 'feplancreacion', 'feplaninivigencia', 'feplanfinvigencia', 'inplancantejemes');
        }

        return array('__isInitialized__', 'inplan', 'txplannombr', 'txplandescripcion', 'inplanvigente', 'inplanfree', 'inplandiasfree', 'feplancreacion', 'feplaninivigencia', 'feplanfinvigencia', 'inplancantejemes');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (LbPlanes $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getInplan()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getInplan();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInplan', array());

        return parent::getInplan();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxplannombr($txplannombr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxplannombr', array($txplannombr));

        return parent::setTxplannombr($txplannombr);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxplannombr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxplannombr', array());

        return parent::getTxplannombr();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxplandescripcion($txplandescripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxplandescripcion', array($txplandescripcion));

        return parent::setTxplandescripcion($txplandescripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxplandescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxplandescripcion', array());

        return parent::getTxplandescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setInplanvigente($inplanvigente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInplanvigente', array($inplanvigente));

        return parent::setInplanvigente($inplanvigente);
    }

    /**
     * {@inheritDoc}
     */
    public function getInplanvigente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInplanvigente', array());

        return parent::getInplanvigente();
    }

    /**
     * {@inheritDoc}
     */
    public function setInplanfree($inplanfree)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInplanfree', array($inplanfree));

        return parent::setInplanfree($inplanfree);
    }

    /**
     * {@inheritDoc}
     */
    public function getInplanfree()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInplanfree', array());

        return parent::getInplanfree();
    }

    /**
     * {@inheritDoc}
     */
    public function setInplandiasfree($inplandiasfree)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInplandiasfree', array($inplandiasfree));

        return parent::setInplandiasfree($inplandiasfree);
    }

    /**
     * {@inheritDoc}
     */
    public function getInplandiasfree()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInplandiasfree', array());

        return parent::getInplandiasfree();
    }

    /**
     * {@inheritDoc}
     */
    public function setFeplancreacion($feplancreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeplancreacion', array($feplancreacion));

        return parent::setFeplancreacion($feplancreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFeplancreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeplancreacion', array());

        return parent::getFeplancreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFeplaninivigencia($feplaninivigencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeplaninivigencia', array($feplaninivigencia));

        return parent::setFeplaninivigencia($feplaninivigencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getFeplaninivigencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeplaninivigencia', array());

        return parent::getFeplaninivigencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setFeplanfinvigencia($feplanfinvigencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeplanfinvigencia', array($feplanfinvigencia));

        return parent::setFeplanfinvigencia($feplanfinvigencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getFeplanfinvigencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeplanfinvigencia', array());

        return parent::getFeplanfinvigencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setInplancantejemes($inplancantejemes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInplancantejemes', array($inplancantejemes));

        return parent::setInplancantejemes($inplancantejemes);
    }

    /**
     * {@inheritDoc}
     */
    public function getInplancantejemes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInplancantejemes', array());

        return parent::getInplancantejemes();
    }

}
