<?php

namespace Proxies\__CG__\Libreame\BackendBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LbHistejemplar extends \Libreame\BackendBundle\Entity\LbHistejemplar implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'inhistejemplar', 'fehisejeregistro', 'inhisejemovimiento', 'inhisejemodoentrega', 'inhisejepadre', 'inhisejeusuario', 'inhisejeejemplar');
        }

        return array('__isInitialized__', 'inhistejemplar', 'fehisejeregistro', 'inhisejemovimiento', 'inhisejemodoentrega', 'inhisejepadre', 'inhisejeusuario', 'inhisejeejemplar');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (LbHistejemplar $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getInhistejemplar()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getInhistejemplar();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInhistejemplar', array());

        return parent::getInhistejemplar();
    }

    /**
     * {@inheritDoc}
     */
    public function setFehisejeregistro($fehisejeregistro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFehisejeregistro', array($fehisejeregistro));

        return parent::setFehisejeregistro($fehisejeregistro);
    }

    /**
     * {@inheritDoc}
     */
    public function getFehisejeregistro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFehisejeregistro', array());

        return parent::getFehisejeregistro();
    }

    /**
     * {@inheritDoc}
     */
    public function setInhisejemovimiento($inhisejemovimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInhisejemovimiento', array($inhisejemovimiento));

        return parent::setInhisejemovimiento($inhisejemovimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getInhisejemovimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInhisejemovimiento', array());

        return parent::getInhisejemovimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setInhisejemodoentrega($inhisejemodoentrega)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInhisejemodoentrega', array($inhisejemodoentrega));

        return parent::setInhisejemodoentrega($inhisejemodoentrega);
    }

    /**
     * {@inheritDoc}
     */
    public function getInhisejemodoentrega()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInhisejemodoentrega', array());

        return parent::getInhisejemodoentrega();
    }

    /**
     * {@inheritDoc}
     */
    public function setInhisejepadre(\Libreame\BackendBundle\Entity\LbHistejemplar $inhisejepadre = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInhisejepadre', array($inhisejepadre));

        return parent::setInhisejepadre($inhisejepadre);
    }

    /**
     * {@inheritDoc}
     */
    public function getInhisejepadre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInhisejepadre', array());

        return parent::getInhisejepadre();
    }

    /**
     * {@inheritDoc}
     */
    public function setInhisejeusuario(\Libreame\BackendBundle\Entity\LbUsuarios $inhisejeusuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInhisejeusuario', array($inhisejeusuario));

        return parent::setInhisejeusuario($inhisejeusuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getInhisejeusuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInhisejeusuario', array());

        return parent::getInhisejeusuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setInhisejeejemplar(\Libreame\BackendBundle\Entity\LbEjemplares $inhisejeejemplar = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInhisejeejemplar', array($inhisejeejemplar));

        return parent::setInhisejeejemplar($inhisejeejemplar);
    }

    /**
     * {@inheritDoc}
     */
    public function getInhisejeejemplar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInhisejeejemplar', array());

        return parent::getInhisejeejemplar();
    }

}
