<?php

namespace Proxies\__CG__\Libreame\BackendBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LbPuntosusuario extends \Libreame\BackendBundle\Entity\LbPuntosusuario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'inidpuus', 'inpuuscantpuntos', 'txpuusmotivo', 'fepuusfechapuntos', 'inpuushiseje', 'inpuususuario');
        }

        return array('__isInitialized__', 'inidpuus', 'inpuuscantpuntos', 'txpuusmotivo', 'fepuusfechapuntos', 'inpuushiseje', 'inpuususuario');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (LbPuntosusuario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getInidpuus()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getInidpuus();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInidpuus', array());

        return parent::getInidpuus();
    }

    /**
     * {@inheritDoc}
     */
    public function setInpuuscantpuntos($inpuuscantpuntos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInpuuscantpuntos', array($inpuuscantpuntos));

        return parent::setInpuuscantpuntos($inpuuscantpuntos);
    }

    /**
     * {@inheritDoc}
     */
    public function getInpuuscantpuntos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInpuuscantpuntos', array());

        return parent::getInpuuscantpuntos();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxpuusmotivo($txpuusmotivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxpuusmotivo', array($txpuusmotivo));

        return parent::setTxpuusmotivo($txpuusmotivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxpuusmotivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxpuusmotivo', array());

        return parent::getTxpuusmotivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setFepuusfechapuntos($fepuusfechapuntos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFepuusfechapuntos', array($fepuusfechapuntos));

        return parent::setFepuusfechapuntos($fepuusfechapuntos);
    }

    /**
     * {@inheritDoc}
     */
    public function getFepuusfechapuntos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFepuusfechapuntos', array());

        return parent::getFepuusfechapuntos();
    }

    /**
     * {@inheritDoc}
     */
    public function setInpuushiseje(\Libreame\BackendBundle\Entity\LbHistejemplar $inpuushiseje = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInpuushiseje', array($inpuushiseje));

        return parent::setInpuushiseje($inpuushiseje);
    }

    /**
     * {@inheritDoc}
     */
    public function getInpuushiseje()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInpuushiseje', array());

        return parent::getInpuushiseje();
    }

    /**
     * {@inheritDoc}
     */
    public function setInpuususuario(\Libreame\BackendBundle\Entity\LbUsuarios $inpuususuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInpuususuario', array($inpuususuario));

        return parent::setInpuususuario($inpuususuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getInpuususuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInpuususuario', array());

        return parent::getInpuususuario();
    }

}
