<?php

namespace Proxies\__CG__\Libreame\BackendBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LbTratos extends \Libreame\BackendBundle\Entity\LbTratos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'intrato', 'intrafecha', 'intraestado', 'txtraacuentrega', 'fetrafecentrega', 'intraoferta', 'intrausuofrecio', 'intrausuacepto');
        }

        return array('__isInitialized__', 'intrato', 'intrafecha', 'intraestado', 'txtraacuentrega', 'fetrafecentrega', 'intraoferta', 'intrausuofrecio', 'intrausuacepto');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (LbTratos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIntrato()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIntrato();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntrato', array());

        return parent::getIntrato();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntrafecha($intrafecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntrafecha', array($intrafecha));

        return parent::setIntrafecha($intrafecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntrafecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntrafecha', array());

        return parent::getIntrafecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntraestado($intraestado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntraestado', array($intraestado));

        return parent::setIntraestado($intraestado);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntraestado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntraestado', array());

        return parent::getIntraestado();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxtraacuentrega($txtraacuentrega)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxtraacuentrega', array($txtraacuentrega));

        return parent::setTxtraacuentrega($txtraacuentrega);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxtraacuentrega()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxtraacuentrega', array());

        return parent::getTxtraacuentrega();
    }

    /**
     * {@inheritDoc}
     */
    public function setFetrafecentrega($fetrafecentrega)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFetrafecentrega', array($fetrafecentrega));

        return parent::setFetrafecentrega($fetrafecentrega);
    }

    /**
     * {@inheritDoc}
     */
    public function getFetrafecentrega()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFetrafecentrega', array());

        return parent::getFetrafecentrega();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntraoferta(\Libreame\BackendBundle\Entity\LbOfertas $intraoferta = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntraoferta', array($intraoferta));

        return parent::setIntraoferta($intraoferta);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntraoferta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntraoferta', array());

        return parent::getIntraoferta();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntrausuofrecio(\Libreame\BackendBundle\Entity\LbUsuarios $intrausuofrecio = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntrausuofrecio', array($intrausuofrecio));

        return parent::setIntrausuofrecio($intrausuofrecio);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntrausuofrecio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntrausuofrecio', array());

        return parent::getIntrausuofrecio();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntrausuacepto(\Libreame\BackendBundle\Entity\LbUsuarios $intrausuacepto = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntrausuacepto', array($intrausuacepto));

        return parent::setIntrausuacepto($intrausuacepto);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntrausuacepto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntrausuacepto', array());

        return parent::getIntrausuacepto();
    }

}
