<?php

namespace Proxies\__CG__\Libreame\BackendBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LbSolicitados extends \Libreame\BackendBundle\Entity\LbSolicitados implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'idsolicitado', 'insoltransac', 'txsolobservacion', 'dbsolvaloferta', 'dbsolvaladic', 'insolejemplar', 'insollibro', 'insoloferta');
        }

        return array('__isInitialized__', 'idsolicitado', 'insoltransac', 'txsolobservacion', 'dbsolvaloferta', 'dbsolvaladic', 'insolejemplar', 'insollibro', 'insoloferta');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (LbSolicitados $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdsolicitado()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdsolicitado();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdsolicitado', array());

        return parent::getIdsolicitado();
    }

    /**
     * {@inheritDoc}
     */
    public function setInsoltransac($insoltransac)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInsoltransac', array($insoltransac));

        return parent::setInsoltransac($insoltransac);
    }

    /**
     * {@inheritDoc}
     */
    public function getInsoltransac()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInsoltransac', array());

        return parent::getInsoltransac();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxsolobservacion($txsolobservacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxsolobservacion', array($txsolobservacion));

        return parent::setTxsolobservacion($txsolobservacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxsolobservacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxsolobservacion', array());

        return parent::getTxsolobservacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDbsolvaloferta($dbsolvaloferta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDbsolvaloferta', array($dbsolvaloferta));

        return parent::setDbsolvaloferta($dbsolvaloferta);
    }

    /**
     * {@inheritDoc}
     */
    public function getDbsolvaloferta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDbsolvaloferta', array());

        return parent::getDbsolvaloferta();
    }

    /**
     * {@inheritDoc}
     */
    public function setDbsolvaladic($dbsolvaladic)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDbsolvaladic', array($dbsolvaladic));

        return parent::setDbsolvaladic($dbsolvaladic);
    }

    /**
     * {@inheritDoc}
     */
    public function getDbsolvaladic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDbsolvaladic', array());

        return parent::getDbsolvaladic();
    }

    /**
     * {@inheritDoc}
     */
    public function setInsolejemplar(\Libreame\BackendBundle\Entity\LbEjemplares $insolejemplar = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInsolejemplar', array($insolejemplar));

        return parent::setInsolejemplar($insolejemplar);
    }

    /**
     * {@inheritDoc}
     */
    public function getInsolejemplar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInsolejemplar', array());

        return parent::getInsolejemplar();
    }

    /**
     * {@inheritDoc}
     */
    public function setInsollibro(\Libreame\BackendBundle\Entity\LbLibros $insollibro = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInsollibro', array($insollibro));

        return parent::setInsollibro($insollibro);
    }

    /**
     * {@inheritDoc}
     */
    public function getInsollibro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInsollibro', array());

        return parent::getInsollibro();
    }

    /**
     * {@inheritDoc}
     */
    public function setInsoloferta(\Libreame\BackendBundle\Entity\LbOfertas $insoloferta = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInsoloferta', array($insoloferta));

        return parent::setInsoloferta($insoloferta);
    }

    /**
     * {@inheritDoc}
     */
    public function getInsoloferta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInsoloferta', array());

        return parent::getInsoloferta();
    }

}
