<?php

namespace Proxies\__CG__\Libreame\BackendBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LbNegociacion extends \Libreame\BackendBundle\Entity\LbNegociacion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'inidnegociacion', 'txnegmensaje', 'innegmensleidosol', 'innegmensleidodue', 'fenegfechamens', 'innegmenseliminado', 'innegejemplar', 'innegusuduenho', 'innegususolicita', 'innegusuescribe', 'txnegidconversacion');
        }

        return array('__isInitialized__', 'inidnegociacion', 'txnegmensaje', 'innegmensleidosol', 'innegmensleidodue', 'fenegfechamens', 'innegmenseliminado', 'innegejemplar', 'innegusuduenho', 'innegususolicita', 'innegusuescribe', 'txnegidconversacion');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (LbNegociacion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getInidnegociacion()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getInidnegociacion();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInidnegociacion', array());

        return parent::getInidnegociacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxnegmensaje($txnegmensaje)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxnegmensaje', array($txnegmensaje));

        return parent::setTxnegmensaje($txnegmensaje);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxnegmensaje()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxnegmensaje', array());

        return parent::getTxnegmensaje();
    }

    /**
     * {@inheritDoc}
     */
    public function setInnegmensleidosol($innegmensleidosol)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInnegmensleidosol', array($innegmensleidosol));

        return parent::setInnegmensleidosol($innegmensleidosol);
    }

    /**
     * {@inheritDoc}
     */
    public function getInnegmensleidosol()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInnegmensleidosol', array());

        return parent::getInnegmensleidosol();
    }

    /**
     * {@inheritDoc}
     */
    public function setInnegmensleidodue($innegmensleidodue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInnegmensleidodue', array($innegmensleidodue));

        return parent::setInnegmensleidodue($innegmensleidodue);
    }

    /**
     * {@inheritDoc}
     */
    public function getInnegmensleidodue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInnegmensleidodue', array());

        return parent::getInnegmensleidodue();
    }

    /**
     * {@inheritDoc}
     */
    public function setFenegfechamens($fenegfechamens)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFenegfechamens', array($fenegfechamens));

        return parent::setFenegfechamens($fenegfechamens);
    }

    /**
     * {@inheritDoc}
     */
    public function getFenegfechamens()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFenegfechamens', array());

        return parent::getFenegfechamens();
    }

    /**
     * {@inheritDoc}
     */
    public function setInnegmenseliminado($innegmenseliminado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInnegmenseliminado', array($innegmenseliminado));

        return parent::setInnegmenseliminado($innegmenseliminado);
    }

    /**
     * {@inheritDoc}
     */
    public function getInnegmenseliminado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInnegmenseliminado', array());

        return parent::getInnegmenseliminado();
    }

    /**
     * {@inheritDoc}
     */
    public function setInnegejemplar(\Libreame\BackendBundle\Entity\LbEjemplares $innegejemplar = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInnegejemplar', array($innegejemplar));

        return parent::setInnegejemplar($innegejemplar);
    }

    /**
     * {@inheritDoc}
     */
    public function getInnegejemplar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInnegejemplar', array());

        return parent::getInnegejemplar();
    }

    /**
     * {@inheritDoc}
     */
    public function setInnegusuduenho(\Libreame\BackendBundle\Entity\LbUsuarios $innegusuduenho = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInnegusuduenho', array($innegusuduenho));

        return parent::setInnegusuduenho($innegusuduenho);
    }

    /**
     * {@inheritDoc}
     */
    public function getInnegusuduenho()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInnegusuduenho', array());

        return parent::getInnegusuduenho();
    }

    /**
     * {@inheritDoc}
     */
    public function setInnegususolicita(\Libreame\BackendBundle\Entity\LbUsuarios $innegususolicita = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInnegususolicita', array($innegususolicita));

        return parent::setInnegususolicita($innegususolicita);
    }

    /**
     * {@inheritDoc}
     */
    public function getInnegususolicita()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInnegususolicita', array());

        return parent::getInnegususolicita();
    }

    /**
     * {@inheritDoc}
     */
    public function setInnegusuescribe(\Libreame\BackendBundle\Entity\LbUsuarios $innegusuescribe = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInnegusuescribe', array($innegusuescribe));

        return parent::setInnegusuescribe($innegusuescribe);
    }

    /**
     * {@inheritDoc}
     */
    public function getInnegusuescribe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInnegusuescribe', array());

        return parent::getInnegusuescribe();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxnegidconversacion($txnegidconversacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxnegidconversacion', array($txnegidconversacion));

        return parent::setTxnegidconversacion($txnegidconversacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxnegidconversacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxnegidconversacion', array());

        return parent::getTxnegidconversacion();
    }

}
