<?php

namespace Proxies\__CG__\Libreame\BackendBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LbOfrecidos extends \Libreame\BackendBundle\Entity\LbOfrecidos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'inofrecido', 'inofrtransac', 'txofrobservacion', 'dbofrvaloferta', 'dbofrvaladic', 'inofrejemplar', 'inofroferta');
        }

        return array('__isInitialized__', 'inofrecido', 'inofrtransac', 'txofrobservacion', 'dbofrvaloferta', 'dbofrvaladic', 'inofrejemplar', 'inofroferta');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (LbOfrecidos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getInofrecido()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getInofrecido();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInofrecido', array());

        return parent::getInofrecido();
    }

    /**
     * {@inheritDoc}
     */
    public function setInofrtransac($inofrtransac)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInofrtransac', array($inofrtransac));

        return parent::setInofrtransac($inofrtransac);
    }

    /**
     * {@inheritDoc}
     */
    public function getInofrtransac()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInofrtransac', array());

        return parent::getInofrtransac();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxofrobservacion($txofrobservacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxofrobservacion', array($txofrobservacion));

        return parent::setTxofrobservacion($txofrobservacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxofrobservacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxofrobservacion', array());

        return parent::getTxofrobservacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDbofrvaloferta($dbofrvaloferta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDbofrvaloferta', array($dbofrvaloferta));

        return parent::setDbofrvaloferta($dbofrvaloferta);
    }

    /**
     * {@inheritDoc}
     */
    public function getDbofrvaloferta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDbofrvaloferta', array());

        return parent::getDbofrvaloferta();
    }

    /**
     * {@inheritDoc}
     */
    public function setDbofrvaladic($dbofrvaladic)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDbofrvaladic', array($dbofrvaladic));

        return parent::setDbofrvaladic($dbofrvaladic);
    }

    /**
     * {@inheritDoc}
     */
    public function getDbofrvaladic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDbofrvaladic', array());

        return parent::getDbofrvaladic();
    }

    /**
     * {@inheritDoc}
     */
    public function setInofrejemplar(\Libreame\BackendBundle\Entity\LbEjemplares $inofrejemplar = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInofrejemplar', array($inofrejemplar));

        return parent::setInofrejemplar($inofrejemplar);
    }

    /**
     * {@inheritDoc}
     */
    public function getInofrejemplar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInofrejemplar', array());

        return parent::getInofrejemplar();
    }

    /**
     * {@inheritDoc}
     */
    public function setInofroferta(\Libreame\BackendBundle\Entity\LbOfertas $inofroferta = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInofroferta', array($inofroferta));

        return parent::setInofroferta($inofroferta);
    }

    /**
     * {@inheritDoc}
     */
    public function getInofroferta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInofroferta', array());

        return parent::getInofroferta();
    }

}
