<?php

namespace Proxies\__CG__\Libreame\BackendBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LbOfertas extends \Libreame\BackendBundle\Entity\LbOfertas implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'inoferta', 'feofefecha', 'inofevigencia', 'inofeactiva', 'inofeabierta', 'inofemembresia');
        }

        return array('__isInitialized__', 'inoferta', 'feofefecha', 'inofevigencia', 'inofeactiva', 'inofeabierta', 'inofemembresia');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (LbOfertas $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getInoferta()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getInoferta();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInoferta', array());

        return parent::getInoferta();
    }

    /**
     * {@inheritDoc}
     */
    public function setFeofefecha($feofefecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeofefecha', array($feofefecha));

        return parent::setFeofefecha($feofefecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFeofefecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeofefecha', array());

        return parent::getFeofefecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setInofevigencia($inofevigencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInofevigencia', array($inofevigencia));

        return parent::setInofevigencia($inofevigencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getInofevigencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInofevigencia', array());

        return parent::getInofevigencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setInofeactiva($inofeactiva)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInofeactiva', array($inofeactiva));

        return parent::setInofeactiva($inofeactiva);
    }

    /**
     * {@inheritDoc}
     */
    public function getInofeactiva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInofeactiva', array());

        return parent::getInofeactiva();
    }

    /**
     * {@inheritDoc}
     */
    public function setInofeabierta($inofeabierta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInofeabierta', array($inofeabierta));

        return parent::setInofeabierta($inofeabierta);
    }

    /**
     * {@inheritDoc}
     */
    public function getInofeabierta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInofeabierta', array());

        return parent::getInofeabierta();
    }

    /**
     * {@inheritDoc}
     */
    public function setInofemembresia(\Libreame\BackendBundle\Entity\LbMembresias $inofemembresia = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInofemembresia', array($inofemembresia));

        return parent::setInofemembresia($inofemembresia);
    }

    /**
     * {@inheritDoc}
     */
    public function getInofemembresia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInofemembresia', array());

        return parent::getInofemembresia();
    }

}
