<?php

namespace Proxies\__CG__\Libreame\BackendBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LbMensajes extends \Libreame\BackendBundle\Entity\LbMensajes implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'inmensaje', 'txmensaje', 'inmenorigen', 'inmenleido', 'inmenfecha', 'inmemidrelacionado', 'inmenfechaleido', 'inmenusuario', 'inmensajepadre', 'inmenusuarioorigen');
        }

        return array('__isInitialized__', 'inmensaje', 'txmensaje', 'inmenorigen', 'inmenleido', 'inmenfecha', 'inmemidrelacionado', 'inmenfechaleido', 'inmenusuario', 'inmensajepadre', 'inmenusuarioorigen');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (LbMensajes $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getInmensaje()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getInmensaje();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInmensaje', array());

        return parent::getInmensaje();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxmensaje($txmensaje)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxmensaje', array($txmensaje));

        return parent::setTxmensaje($txmensaje);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxmensaje()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxmensaje', array());

        return parent::getTxmensaje();
    }

    /**
     * {@inheritDoc}
     */
    public function setInmenorigen($inmenorigen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInmenorigen', array($inmenorigen));

        return parent::setInmenorigen($inmenorigen);
    }

    /**
     * {@inheritDoc}
     */
    public function getInmenorigen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInmenorigen', array());

        return parent::getInmenorigen();
    }

    /**
     * {@inheritDoc}
     */
    public function setInmenleido($inmenleido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInmenleido', array($inmenleido));

        return parent::setInmenleido($inmenleido);
    }

    /**
     * {@inheritDoc}
     */
    public function getInmenleido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInmenleido', array());

        return parent::getInmenleido();
    }

    /**
     * {@inheritDoc}
     */
    public function setInmenfecha($inmenfecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInmenfecha', array($inmenfecha));

        return parent::setInmenfecha($inmenfecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getInmenfecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInmenfecha', array());

        return parent::getInmenfecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setInmemidrelacionado($inmemidrelacionado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInmemidrelacionado', array($inmemidrelacionado));

        return parent::setInmemidrelacionado($inmemidrelacionado);
    }

    /**
     * {@inheritDoc}
     */
    public function getInmemidrelacionado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInmemidrelacionado', array());

        return parent::getInmemidrelacionado();
    }

    /**
     * {@inheritDoc}
     */
    public function setInmenfechaleido($inmenfechaleido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInmenfechaleido', array($inmenfechaleido));

        return parent::setInmenfechaleido($inmenfechaleido);
    }

    /**
     * {@inheritDoc}
     */
    public function getInmenfechaleido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInmenfechaleido', array());

        return parent::getInmenfechaleido();
    }

    /**
     * {@inheritDoc}
     */
    public function setInmenusuario(\Libreame\BackendBundle\Entity\LbUsuarios $inmenusuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInmenusuario', array($inmenusuario));

        return parent::setInmenusuario($inmenusuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getInmenusuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInmenusuario', array());

        return parent::getInmenusuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setInmenusuarioorigen(\Libreame\BackendBundle\Entity\LbUsuarios $inmenusuarioorigen = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInmenusuarioorigen', array($inmenusuarioorigen));

        return parent::setInmenusuarioorigen($inmenusuarioorigen);
    }

    /**
     * {@inheritDoc}
     */
    public function getInmenusuarioorigen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInmenusuarioorigen', array());

        return parent::getInmenusuarioorigen();
    }

    /**
     * {@inheritDoc}
     */
    public function setInmensajepadre(\Libreame\BackendBundle\Entity\LbMensajes $inmensajepadre = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInmensajepadre', array($inmensajepadre));

        return parent::setInmensajepadre($inmensajepadre);
    }

    /**
     * {@inheritDoc}
     */
    public function getInmensajepadre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInmensajepadre', array());

        return parent::getInmensajepadre();
    }

}
