<?php

namespace Proxies\__CG__\Libreame\BackendBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LbDetallestratos extends \Libreame\BackendBundle\Entity\LbDetallestratos implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'indetalletrato', 'indetvalorusr', 'indetvalorotro', 'indetejemplarusr', 'indetejemplarotro', 'indettrato', 'indetusuario', 'indetusuariootro');
        }

        return array('__isInitialized__', 'indetalletrato', 'indetvalorusr', 'indetvalorotro', 'indetejemplarusr', 'indetejemplarotro', 'indettrato', 'indetusuario', 'indetusuariootro');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (LbDetallestratos $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIndetalletrato()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIndetalletrato();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndetalletrato', array());

        return parent::getIndetalletrato();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndetvalorusr($indetvalorusr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndetvalorusr', array($indetvalorusr));

        return parent::setIndetvalorusr($indetvalorusr);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndetvalorusr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndetvalorusr', array());

        return parent::getIndetvalorusr();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndetvalorotro($indetvalorotro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndetvalorotro', array($indetvalorotro));

        return parent::setIndetvalorotro($indetvalorotro);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndetvalorotro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndetvalorotro', array());

        return parent::getIndetvalorotro();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndetejemplarusr(\Libreame\BackendBundle\Entity\LbEjemplares $indetejemplarusr = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndetejemplarusr', array($indetejemplarusr));

        return parent::setIndetejemplarusr($indetejemplarusr);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndetejemplarusr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndetejemplarusr', array());

        return parent::getIndetejemplarusr();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndetejemplarotro(\Libreame\BackendBundle\Entity\LbEjemplares $indetejemplarotro = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndetejemplarotro', array($indetejemplarotro));

        return parent::setIndetejemplarotro($indetejemplarotro);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndetejemplarotro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndetejemplarotro', array());

        return parent::getIndetejemplarotro();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndettrato(\Libreame\BackendBundle\Entity\LbTratos $indettrato = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndettrato', array($indettrato));

        return parent::setIndettrato($indettrato);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndettrato()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndettrato', array());

        return parent::getIndettrato();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndetusuario(\Libreame\BackendBundle\Entity\LbUsuarios $indetusuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndetusuario', array($indetusuario));

        return parent::setIndetusuario($indetusuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndetusuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndetusuario', array());

        return parent::getIndetusuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndetusuariootro(\Libreame\BackendBundle\Entity\LbUsuarios $indetusuariootro = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndetusuariootro', array($indetusuariootro));

        return parent::setIndetusuariootro($indetusuariootro);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndetusuariootro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndetusuariootro', array());

        return parent::getIndetusuariootro();
    }

}
