parameters:
#    libreame_backend.example.class: Libreame\BackendBundle\Example

services:
#    libreame_backend.example:
#        class: %libreame_backend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
