parameters:
#    libreame_backend.example.class: Libreame\BackendBundle\Example

services:
    #Servicio para acciones comunes y llamado a funciones de negocio
    logica_service:
        class: Libreame\BackendBundle\Helpers\Logica
#        arguments: [@service_id, "plain_value", %parameter%]

    #Servicio principal publico, por el cual se puede acceder a cualquier funcionalidad del sistema
    acceso_service:
        class: Libreame\BackendBundle\Controller\AccesoController
#        arguments: [@service_id, "plain_value", %parameter%]

    #Servicio que contiene los metodos para registrarse (darse de alta) en el sistema
    registro_service:
        class: Libreame\BackendBundle\Helpers\Registro
#        arguments: [@service_id, "plain_value", %parameter%]

    #Servicio que contiene los metodos para ingresar y salir del sistema(Login, Logout)
    login_service:
        class: Libreame\BackendBundle\Helpers\Login
#        arguments: [@service_id, "plain_value", %parameter%]

    #Servicio que contiene los metodos para obtener los datos de un usuario (Pestaña de PREFERENCIAS)
    parametros_service:
        class: Libreame\BackendBundle\Helpers\Parametros
#        arguments: [@service_id, "plain_value", %parameter%]

    #Servicio que contiene los metodos para recu´perar los feed de Ejemplares subidos a la plataforma
    feeds_service:
        class: Libreame\BackendBundle\Helpers\FeedEjemplares
#        arguments: [@service_id, "plain_value", %parameter%]

