parameters:
#    libreame_backend.example.class: Libreame\BackendBundle\Example

services:
    logica_service:
        class: Libreame\BackendBundle\Helpers\Logica
#        arguments: [@service_id, "plain_value", %parameter%]

    acceso_service:
        class: Libreame\BackendBundle\Controller\AccesoController
#        arguments: [@service_id, "plain_value", %parameter%]

    registro_service:
        class: Libreame\BackendBundle\Helpers\Registro
#        arguments: [@service_id, "plain_value", %parameter%]
